//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	edgev1alpha1 "github.com/kubestellar/kubestellar/pkg/apis/edge/v1alpha1"
	scopedclientset "github.com/kubestellar/kubestellar/pkg/client/clientset/versioned"
	clientset "github.com/kubestellar/kubestellar/pkg/client/clientset/versioned/cluster"
	"github.com/kubestellar/kubestellar/pkg/client/informers/externalversions/internalinterfaces"
	edgev1alpha1listers "github.com/kubestellar/kubestellar/pkg/client/listers/edge/v1alpha1"
)

// SinglePlacementSliceClusterInformer provides access to a shared informer and lister for
// SinglePlacementSlices.
type SinglePlacementSliceClusterInformer interface {
	Cluster(logicalcluster.Name) SinglePlacementSliceInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() edgev1alpha1listers.SinglePlacementSliceClusterLister
}

type singlePlacementSliceClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSinglePlacementSliceClusterInformer constructs a new informer for SinglePlacementSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSinglePlacementSliceClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredSinglePlacementSliceClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSinglePlacementSliceClusterInformer constructs a new informer for SinglePlacementSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSinglePlacementSliceClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().SinglePlacementSlices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().SinglePlacementSlices().Watch(context.TODO(), options)
			},
		},
		&edgev1alpha1.SinglePlacementSlice{},
		resyncPeriod,
		indexers,
	)
}

func (f *singlePlacementSliceClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredSinglePlacementSliceClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
	},
		f.tweakListOptions,
	)
}

func (f *singlePlacementSliceClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&edgev1alpha1.SinglePlacementSlice{}, f.defaultInformer)
}

func (f *singlePlacementSliceClusterInformer) Lister() edgev1alpha1listers.SinglePlacementSliceClusterLister {
	return edgev1alpha1listers.NewSinglePlacementSliceClusterLister(f.Informer().GetIndexer())
}

// SinglePlacementSliceInformer provides access to a shared informer and lister for
// SinglePlacementSlices.
type SinglePlacementSliceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() edgev1alpha1listers.SinglePlacementSliceLister
}

func (f *singlePlacementSliceClusterInformer) Cluster(clusterName logicalcluster.Name) SinglePlacementSliceInformer {
	return &singlePlacementSliceInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type singlePlacementSliceInformer struct {
	informer cache.SharedIndexInformer
	lister   edgev1alpha1listers.SinglePlacementSliceLister
}

func (f *singlePlacementSliceInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *singlePlacementSliceInformer) Lister() edgev1alpha1listers.SinglePlacementSliceLister {
	return f.lister
}

type singlePlacementSliceScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

func (f *singlePlacementSliceScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&edgev1alpha1.SinglePlacementSlice{}, f.defaultInformer)
}

func (f *singlePlacementSliceScopedInformer) Lister() edgev1alpha1listers.SinglePlacementSliceLister {
	return edgev1alpha1listers.NewSinglePlacementSliceLister(f.Informer().GetIndexer())
}

// NewSinglePlacementSliceInformer constructs a new informer for SinglePlacementSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSinglePlacementSliceInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSinglePlacementSliceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSinglePlacementSliceInformer constructs a new informer for SinglePlacementSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSinglePlacementSliceInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().SinglePlacementSlices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().SinglePlacementSlices().Watch(context.TODO(), options)
			},
		},
		&edgev1alpha1.SinglePlacementSlice{},
		resyncPeriod,
		indexers,
	)
}

func (f *singlePlacementSliceScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSinglePlacementSliceInformer(client, resyncPeriod, cache.Indexers{}, f.tweakListOptions)
}
