actions/checkout:
  sha: de0fac2e4500dabe0009e67214ff5f5447ce83dd
  sha-url: https://github.com/actions/checkout/commit/de0fac2e4500dabe0009e67214ff5f5447ce83dd
  tag: v6.0.2
  tag-url: https://github.com/actions/checkout/tree/v6.0.2
actions/stale:
  sha: 997185467fa4f803885201cee163a9f38240193d
  sha-url: https://github.com/actions/stale/commit/997185467fa4f803885201cee163a9f38240193d
  tag: v10.1.1
  tag-url: https://github.com/actions/stale/tree/v10.1.1
actions/add-to-project:
  sha: 244f685bbc3b7adfa8466e08b698b5577571133e
  sha-url: https://github.com/actions/add-to-project/commit/244f685bbc3b7adfa8466e08b698b5577571133e
  tag: v1.0.2
  tag-url: https://github.com/actions/add-to-project/tree/v1.0.2
titoportas/update-project-fields:
  sha: 421a54430b3cdc9eefd8f14f9ce0142ab7678751
  sha-url: https://github.com/titoportas/update-project-fields/commit/421a54430b3cdc9eefd8f14f9ce0142ab7678751
  tag: v0.1.0
  tag-url: https://github.com/titoportas/update-project-fields/tree/v0.1.0
ScholliYT/Broken-Links-Crawler-Action:
  sha: 21eab52f98097989d343116dbbd46dc4541b849b
  sha-url: https://github.com/ScholliYT/Broken-Links-Crawler-Action/commit/21eab52f98097989d343116dbbd46dc4541b849b
  tag: v3.3.2
  tag-url: https://github.com/ScholliYT/Broken-Links-Crawler-Action/tree/v3.3.2
JasonEtco/create-an-issue:
  sha: 1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
  sha-url: https://github.com/JasonEtco/create-an-issue/commit/1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
  tag: v2
  tag-url: https://github.com/JasonEtco/create-an-issue/tree/v2
actions/setup-python:
  sha: a309ff8b426b58ec0e2a45f0f869d46889d02405
  sha-url: https://github.com/actions/setup-python/commit/a309ff8b426b58ec0e2a45f0f869d46889d02405
  tag: v6.2.0
  tag-url: https://github.com/actions/setup-python/tree/v6.2.0
actions/setup-go:
  sha: 7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
  sha-url: https://github.com/actions/setup-go/commit/7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
  tag: v6.2.0
  tag-url: https://github.com/actions/setup-go/tree/v6.2.0
anchore/sbom-action/download-syft:
  sha: 0b82b0b1a22399a1c542d4d656f70cd903571b5c
  sha-url: https://github.com/anchore/sbom-action/commit/0b82b0b1a22399a1c542d4d656f70cd903571b5c
  tag: v0.21.1
  tag-url: https://github.com/anchore/sbom-action/tree/v0.21.1
goreleaser/goreleaser-action:
  sha: e435ccd777264be153ace6237001ef4d979d3a7a
  sha-url: https://github.com/goreleaser/goreleaser-action/commit/e435ccd777264be153ace6237001ef4d979d3a7a
  tag: v6.4.0
  tag-url: https://github.com/goreleaser/goreleaser-action/tree/v6.4.0
azure/setup-helm:
  sha: 1a275c3b69536ee54be43f2070a358922e12c8d4
  sha-url: https://github.com/azure/setup-helm/commit/1a275c3b69536ee54be43f2070a358922e12c8d4
  tag: v4.3.1
  tag-url: https://github.com/azure/setup-helm/tree/v4.3.1
docker/login-action:
  sha: c94ce9fb468520275223c153574b00df6fe4bcc9
  sha-url: https://github.com/docker/login-action/commit/c94ce9fb468520275223c153574b00df6fe4bcc9
  tag: v3.7.0
  tag-url: https://github.com/docker/login-action/tree/v3.7.0
actions/first-interaction:
  sha: 1c4688942c71f71d4f5502a26ea67c331730fa4d
  sha-url: https://github.com/actions/first-interaction/commit/1c4688942c71f71d4f5502a26ea67c331730fa4d
  tag: v3.1.0
  tag-url: https://github.com/actions/first-interaction/tree/v3.1.0
azure/setup-kubectl:
  sha: 776406bce94f63e41d621b960d78ee25c8b76ede
  sha-url: https://github.com/azure/setup-kubectl/commit/776406bce94f63e41d621b960d78ee25c8b76ede
  tag: v4.0.1
  tag-url: https://github.com/azure/setup-kubectl/tree/v4.0.1
ko-build/setup-ko:
  sha: d006021bd0c28d1ce33a07e7943d48b079944c8d
  sha-url: https://github.com/ko-build/setup-ko/commit/d006021bd0c28d1ce33a07e7943d48b079944c8d
  tag: v0.9
  tag-url: https://github.com/ko-build/setup-ko/tree/v0.9
peter-evans/create-or-update-comment:
  sha: e8674b075228eee787fea43ef493e45ece1004c9
  sha-url: https://github.com/peter-evans/create-or-update-comment/commit/e8674b075228eee787fea43ef493e45ece1004c9
  tag: v5.0.0
  tag-url: https://github.com/peter-evans/create-or-update-comment/tree/v5.0.0
peter-evans/repository-dispatch:
  sha: 28959ce8df70de7be546dd1250a005dd32156697
  sha-url: https://github.com/peter-evans/repository-dispatch/commit/28959ce8df70de7be546dd1250a005dd32156697
  tag: v4.0.1
  tag-url: https://github.com/peter-evans/repository-dispatch/tree/v4.0.1
technote-space/assign-author:
  sha: 9558557c5c4816f38bd06176fbc324ba14bb3160
  sha-url: https://github.com/technote-space/assign-author/commit/9558557c5c4816f38bd06176fbc324ba14bb3160
  tag: v1.6.2
  tag-url: https://github.com/technote-space/assign-author/tree/v1.6.2
rojopolis/spellcheck-github-actions:
  sha: cebe06444da3ac5e9d3146f5f02a0e2a236f7488
  sha-url: https://github.com/rojopolis/spellcheck-github-actions/commit/cebe06444da3ac5e9d3146f5f02a0e2a236f7488
  tag: 0.56.0
  tag-url: https://github.com/rojopolis/spellcheck-github-actions/tree/0.56.0
actions/upload-artifact:
  sha: b7c566a772e6b6bfb58ed0dc250532a479d7789f
  sha-url: https://github.com/actions/upload-artifact/commit/b7c566a772e6b6bfb58ed0dc250532a479d7789f
  tag: v6.0.0
  tag-url: https://github.com/actions/upload-artifact/tree/v6.0.0
actions/github-script:
  sha: ed597411d8f924073f98dfc5c65a23a2325f34cd
  sha-url: https://github.com/actions/github-script/commit/ed597411d8f924073f98dfc5c65a23a2325f34cd
  tag: v8
  tag-url: https://github.com/actions/github-script/tree/v8
ossf/scorecard-action:
  sha: 4eaacf0543bb3f2c246792bd56e8cdeffafb205a
  sha-url: https://github.com/ossf/scorecard-action/commit/4eaacf0543bb3f2c246792bd56e8cdeffafb205a
  tag: v2.4.3
  tag-url: https://github.com/ossf/scorecard-action/tree/v2.4.3
aquasecurity/trivy-action:
  sha: b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
  sha-url: https://github.com/aquasecurity/trivy-action/commit/b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
  tag: 0.33.1
  tag-url: https://github.com/aquasecurity/trivy-action/tree/0.33.1
github/codeql-action/upload-sarif:
  sha: 45c373516f557556c15d420e3f5e0aa3d64366bc
  sha-url: https://github.com/github/codeql-action/commit/45c373516f557556c15d420e3f5e0aa3d64366bc
  tag: v3.31.9
  tag-url: https://github.com/github/codeql-action/tree/v3.31.9
