actions/checkout:
  sha: 8e8c483db84b4bee98b60c0593521ed34d9990e8
  sha-url: https://github.com/actions/checkout/commit/8e8c483db84b4bee98b60c0593521ed34d9990e8
  tag: v6.0.1
  tag-url: https://github.com/actions/checkout/tree/v6.0.1
actions/stale:
  sha: 997185467fa4f803885201cee163a9f38240193d
  sha-url: https://github.com/actions/stale/commit/997185467fa4f803885201cee163a9f38240193d
  tag: v10.1.1
  tag-url: https://github.com/actions/stale/tree/v10.1.1
actions/add-to-project:
  sha: 244f685bbc3b7adfa8466e08b698b5577571133e
  sha-url: https://github.com/actions/add-to-project/commit/244f685bbc3b7adfa8466e08b698b5577571133e
  tag: v1.0.2
  tag-url: https://github.com/actions/add-to-project/tree/v1.0.2
titoportas/update-project-fields:
  sha: 421a54430b3cdc9eefd8f14f9ce0142ab7678751
  sha-url: https://github.com/titoportas/update-project-fields/commit/421a54430b3cdc9eefd8f14f9ce0142ab7678751
  tag: v0.1.0
  tag-url: https://github.com/titoportas/update-project-fields/tree/v0.1.0
ScholliYT/Broken-Links-Crawler-Action:
  sha: b3fb123879e5a6a854d6fda5c33df2d94d41092c
  sha-url: https://github.com/ScholliYT/Broken-Links-Crawler-Action/commit/b3fb123879e5a6a854d6fda5c33df2d94d41092c
  tag: v3.3.1
  tag-url: https://github.com/ScholliYT/Broken-Links-Crawler-Action/tree/v3.3.1
JasonEtco/create-an-issue:
  sha: 1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
  sha-url: https://github.com/JasonEtco/create-an-issue/commit/1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
  tag: v2
  tag-url: https://github.com/JasonEtco/create-an-issue/tree/v2
actions/setup-python:
  sha: 83679a892e2d95755f2dac6acb0bfd1e9ac5d548
  sha-url: https://github.com/actions/setup-python/commit/83679a892e2d95755f2dac6acb0bfd1e9ac5d548
  tag: v6.1.0
  tag-url: https://github.com/actions/setup-python/tree/v6.1.0
actions/setup-go:
  sha: 4dc6199c7b1a012772edbd06daecab0f50c9053c
  sha-url: https://github.com/actions/setup-go/commit/4dc6199c7b1a012772edbd06daecab0f50c9053c
  tag: v6.1.0
  tag-url: https://github.com/actions/setup-go/tree/v6.1.0
anchore/sbom-action/download-syft:
  sha: fbfd9c6c189226748411491745178e0c2017392d
  sha-url: https://github.com/anchore/sbom-action/commit/fbfd9c6c189226748411491745178e0c2017392d
  tag: v0.20.10
  tag-url: https://github.com/anchore/sbom-action/tree/v0.20.10
goreleaser/goreleaser-action:
  sha: e435ccd777264be153ace6237001ef4d979d3a7a
  sha-url: https://github.com/goreleaser/goreleaser-action/commit/e435ccd777264be153ace6237001ef4d979d3a7a
  tag: v6.4.0
  tag-url: https://github.com/goreleaser/goreleaser-action/tree/v6.4.0
azure/setup-helm:
  sha: 1a275c3b69536ee54be43f2070a358922e12c8d4
  sha-url: https://github.com/azure/setup-helm/commit/1a275c3b69536ee54be43f2070a358922e12c8d4
  tag: v4.3.1
  tag-url: https://github.com/azure/setup-helm/tree/v4.3.1
docker/login-action:
  sha: 5e57cd118135c172c3672efd75eb46360885c0ef
  sha-url: https://github.com/docker/login-action/commit/5e57cd118135c172c3672efd75eb46360885c0ef
  tag: v3.6.0
  tag-url: https://github.com/docker/login-action/tree/v3.6.0
actions/first-interaction:
  sha: 1c4688942c71f71d4f5502a26ea67c331730fa4d
  sha-url: https://github.com/actions/first-interaction/commit/1c4688942c71f71d4f5502a26ea67c331730fa4d
  tag: v3.1.0
  tag-url: https://github.com/actions/first-interaction/tree/v3.1.0
azure/setup-kubectl:
  sha: 776406bce94f63e41d621b960d78ee25c8b76ede
  sha-url: https://github.com/azure/setup-kubectl/commit/776406bce94f63e41d621b960d78ee25c8b76ede
  tag: v4.0.1
  tag-url: https://github.com/azure/setup-kubectl/tree/v4.0.1
ko-build/setup-ko:
  sha: d006021bd0c28d1ce33a07e7943d48b079944c8d
  sha-url: https://github.com/ko-build/setup-ko/commit/d006021bd0c28d1ce33a07e7943d48b079944c8d
  tag: v0.9
  tag-url: https://github.com/ko-build/setup-ko/tree/v0.9
peter-evans/create-or-update-comment:
  sha: e8674b075228eee787fea43ef493e45ece1004c9
  sha-url: https://github.com/peter-evans/create-or-update-comment/commit/e8674b075228eee787fea43ef493e45ece1004c9
  tag: v5.0.0
  tag-url: https://github.com/peter-evans/create-or-update-comment/tree/v5.0.0
technote-space/assign-author:
  sha: 9558557c5c4816f38bd06176fbc324ba14bb3160
  sha-url: https://github.com/technote-space/assign-author/commit/9558557c5c4816f38bd06176fbc324ba14bb3160
  tag: v1.6.2
  tag-url: https://github.com/technote-space/assign-author/tree/v1.6.2
rojopolis/spellcheck-github-actions:
  sha: 16d0338a5a3b5e3111a078029fb9a07a8125053d
  sha-url: https://github.com/rojopolis/spellcheck-github-actions/commit/16d0338a5a3b5e3111a078029fb9a07a8125053d
  tag: 0.55.0
  tag-url: https://github.com/rojopolis/spellcheck-github-actions/tree/0.55.0
actions/upload-artifact:
  sha: 330a01c490aca151604b8cf639adc76d48f6c5d4
  sha-url: https://github.com/actions/upload-artifact/commit/330a01c490aca151604b8cf639adc76d48f6c5d4
  tag: v5.0.0
  tag-url: https://github.com/actions/upload-artifact/tree/v5.0.0
actions/github-script:
  sha: ed597411d8f924073f98dfc5c65a23a2325f34cd
  sha-url: https://github.com/actions/github-script/commit/ed597411d8f924073f98dfc5c65a23a2325f34cd
  tag: v8
  tag-url: https://github.com/actions/github-script/tree/v8
