actions/checkout:
  sha: 08c6903cd8c0fde910a37f88322edcfb5dd907a8
  sha-url: https://github.com/actions/checkout/commit/08c6903cd8c0fde910a37f88322edcfb5dd907a8
  tag: v5.0.0
  tag-url: https://github.com/actions/checkout/tree/v5.0.0
actions/stale:
  sha: 3a9db7e6a41a89f618792c92c0e97cc736e1b13f
  sha-url: https://github.com/actions/stale/commit/3a9db7e6a41a89f618792c92c0e97cc736e1b13f
  tag: v10.0.0
  tag-url: https://github.com/actions/stale/tree/v10.0.0
actions/add-to-project:
  sha: 244f685bbc3b7adfa8466e08b698b5577571133e
  sha-url: https://github.com/actions/add-to-project/commit/244f685bbc3b7adfa8466e08b698b5577571133e
  tag: v1.0.2
  tag-url: https://github.com/actions/add-to-project/tree/v1.0.2
titoportas/update-project-fields:
  sha: 421a54430b3cdc9eefd8f14f9ce0142ab7678751
  sha-url: https://github.com/titoportas/update-project-fields/commit/421a54430b3cdc9eefd8f14f9ce0142ab7678751
  tag: v0.1.0
  tag-url: https://github.com/titoportas/update-project-fields/tree/v0.1.0
ScholliYT/Broken-Links-Crawler-Action:
  sha: b3fb123879e5a6a854d6fda5c33df2d94d41092c
  sha-url: https://github.com/ScholliYT/Broken-Links-Crawler-Action/commit/b3fb123879e5a6a854d6fda5c33df2d94d41092c
  tag: v3.3.1
  tag-url: https://github.com/ScholliYT/Broken-Links-Crawler-Action/tree/v3.3.1
JasonEtco/create-an-issue:
  sha: 1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
  sha-url: https://github.com/JasonEtco/create-an-issue/commit/1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
  tag: v2
  tag-url: https://github.com/JasonEtco/create-an-issue/tree/v2
actions/setup-python:
  sha: e797f83bcb11b83ae66e0230d6156d7c80228e7c
  sha-url: https://github.com/actions/setup-python/commit/e797f83bcb11b83ae66e0230d6156d7c80228e7c
  tag: v6.0.0
  tag-url: https://github.com/actions/setup-python/tree/v6.0.0
actions/setup-go:
  sha: 44694675825211faa026b3c33043df3e48a5fa00
  sha-url: https://github.com/actions/setup-go/commit/44694675825211faa026b3c33043df3e48a5fa00
  tag: v6.0.0
  tag-url: https://github.com/actions/setup-go/tree/v6.0.0
anchore/sbom-action/download-syft:
  sha: da167eac915b4e86f08b264dbdbc867b61be6f0c
  sha-url: https://github.com/anchore/sbom-action/commit/da167eac915b4e86f08b264dbdbc867b61be6f0c
  tag: v0.20.5
  tag-url: https://github.com/anchore/sbom-action/tree/v0.20.5
goreleaser/goreleaser-action:
  sha: e435ccd777264be153ace6237001ef4d979d3a7a
  sha-url: https://github.com/goreleaser/goreleaser-action/commit/e435ccd777264be153ace6237001ef4d979d3a7a
  tag: v6.4.0
  tag-url: https://github.com/goreleaser/goreleaser-action/tree/v6.4.0
azure/setup-helm:
  sha: 1a275c3b69536ee54be43f2070a358922e12c8d4
  sha-url: https://github.com/azure/setup-helm/commit/1a275c3b69536ee54be43f2070a358922e12c8d4
  tag: v4.3.1
  tag-url: https://github.com/azure/setup-helm/tree/v4.3.1
docker/login-action:
  sha: 184bdaa0721073962dff0199f1fb9940f07167d1
  sha-url: https://github.com/docker/login-action/commit/184bdaa0721073962dff0199f1fb9940f07167d1
  tag: v3.5.0
  tag-url: https://github.com/docker/login-action/tree/v3.5.0
actions/first-interaction:
  sha: 753c925c8d1ac6fede23781875376600628d9b5d
  sha-url: https://github.com/actions/first-interaction/commit/753c925c8d1ac6fede23781875376600628d9b5d
  tag: v3.0.0
  tag-url: https://github.com/actions/first-interaction/tree/v3.0.0
azure/setup-kubectl:
  sha: 776406bce94f63e41d621b960d78ee25c8b76ede
  sha-url: https://github.com/azure/setup-kubectl/commit/776406bce94f63e41d621b960d78ee25c8b76ede
  tag: v4.0.1
  tag-url: https://github.com/azure/setup-kubectl/tree/v4.0.1
ko-build/setup-ko:
  sha: d006021bd0c28d1ce33a07e7943d48b079944c8d
  sha-url: https://github.com/ko-build/setup-ko/commit/d006021bd0c28d1ce33a07e7943d48b079944c8d
  tag: v0.9
  tag-url: https://github.com/ko-build/setup-ko/tree/v0.9
technote-space/assign-author:
  sha: 9558557c5c4816f38bd06176fbc324ba14bb3160
  sha-url: https://github.com/technote-space/assign-author/commit/9558557c5c4816f38bd06176fbc324ba14bb3160
  tag: v1.6.2
  tag-url: https://github.com/technote-space/assign-author/tree/v1.6.2
rojopolis/spellcheck-github-actions:
  sha: 35a02bae020e6999c5c37fabaf447f2eb8822ca7
  sha-url: https://github.com/rojopolis/spellcheck-github-actions/commit/35a02bae020e6999c5c37fabaf447f2eb8822ca7
  tag: 0.51.0
  tag-url: https://github.com/rojopolis/spellcheck-github-actions/tree/0.51.0
actions/upload-artifact:
  sha: ea165f8d65b6e75b540449e92b4886f43607fa02
  sha-url: https://github.com/actions/upload-artifact/commit/ea165f8d65b6e75b540449e92b4886f43607fa02
  tag: v4
  tag-url: https://github.com/actions/upload-artifact/tree/v4
actions/github-script:
  sha: ed597411d8f924073f98dfc5c65a23a2325f34cd
  sha-url: https://github.com/actions/github-script/commit/ed597411d8f924073f98dfc5c65a23a2325f34cd
  tag: v8
  tag-url: https://github.com/actions/github-script/tree/v8
