version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - errorlint
    - importas
    - misspell
    - nilerr
    - nolintlint
    - unconvert
    - govet
    - staticcheck
    - ineffassign
    - unused
  settings:
    misspell:
      ignore-rules:
        - creater
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: "SA1019:"
      - linters:
          - staticcheck
        text: "ST"
      - linters:
          - staticcheck
        text: "QF"
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
