presubmits:
  - name: pull-kubestellar-verify
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.20.13-1
          command:
            - make
            - verify-boilerplate
            - verify-codegen
            - verify-go-versions
            - verify-imports
            - verify-modules
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-kubestellar-lint
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.20.13-1
          command:
            - make
            - lint
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-kubestellar-test-unit
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.20.13-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: '1'
          resources:
            requests:
              memory: 4Gi
              cpu: 2
