presubmits:
  - name: pull-kubestellar-verify
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - make
            - verify-boilerplate
            - verify-codegen
            - verify-go-versions
            - verify-imports
            - verify-modules
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-kubestellar-lint
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - make
            - lint
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-kubestellar-test-unit
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: "1"
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-kubestellar-test-demo-env-kind
    always_run: false
    optional: true
    run_if_changed: "^scripts/create-kubestellar-demo-env\\.sh$"
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - ./test/e2e/ci/test-demo-env.sh
            - kind
          resources:
            requests:
              memory: 8Gi
              cpu: 4

  - name: pull-kubestellar-test-demo-env-k3d
    always_run: false
    optional: true
    run_if_changed: "^scripts/create-kubestellar-demo-env\\.sh$"
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - ./test/e2e/ci/test-demo-env.sh
            - k3d
          resources:
            requests:
              memory: 8Gi
              cpu: 4
