{
 "title": "API Server Priority & Fairness",
 "description": "Dashboards for obsessive people",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "SpaceNS", "query": "wds1-system" },
   { "name": "APIService", "query": "wds1" }
  ]
 },
 "panels": [
  {
   "title": "Total inflight request",
   "type": "timeseries",
   "description": "Request rate by error code",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(max_over_time(apiserver_current_inflight_requests{job=\"$APIService\", namespace=\"$SpaceNS\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Advanced Priority and Fairness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Shared concurrency limit by priority group",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max without(instance)(apiserver_flowcontrol_request_concurrency_limit{job=\"$APIService\", namespace=\"$SpaceNS\"})",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "% of priority level max shares used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * max by (priority_level)(apiserver_flowcontrol_current_executing_requests{job=\"$APIService\", namespace=\"$SpaceNS\"}) / max by (priority_level) (apiserver_flowcontrol_request_concurrency_limit{job=\"$APIService\", namespace=\"$SpaceNS\"}) ",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Top executing requests by Flow",
   "type": "timeseries",
   "description": "Number of requests in initial (for a WATCH) or any (for a non-WATCH) execution stage in the API Priority and Fairness subsystem",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max without (endpoint,namespace,service) (apiserver_flowcontrol_current_executing_requests{job=\"$APIService\", namespace=\"$SpaceNS\"}))",
     "legendFormat": "Flow: {{flow_schema}} --Priority Level: {{priority_level}} -- {{instance}}"
    }
   ]
  },
  {
   "title": "Time Request was in queue by flowschema (p90) - Top Instance",
   "type": "timeseries",
   "description": "Length of time a request spent waiting in its queue - Max of APIservers",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, max without (instance) (increase(apiserver_flowcontrol_request_wait_duration_seconds_bucket{job=\"$APIService\", namespace=\"$SpaceNS\"}[$__rate_interval])))",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "Flowcontrol request execution time p90 - Top Instance",
   "type": "timeseries",
   "description": "Duration of initial stage (for a WATCH) or any (for a non-WATCH) stage of request execution in the API Priority and Fairness subsystem",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, max without (instance) (increase(apiserver_flowcontrol_request_execution_seconds_bucket{job=\"$APIService\", namespace=\"$SpaceNS\"}[$__rate_interval])))",
     "legendFormat": "{{flow_schema}} - {{priority_level}}"
    }
   ]
  },
  {
   "title": "Rate of addition per second",
   "type": "timeseries",
   "description": "Length of queue in the API Priority and Fairness subsystem, as seen by each request after it is enqueued",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "topk(5, sum by (instance,priority_level,flow_schema)(rate(apiserver_flowcontrol_request_queue_length_after_enqueue_count{job=\"$APIService\", namespace=\"$SpaceNS\"}[$__rate_interval])))",
     "legendFormat": "Flow: {{flow_schema}} --Priority: {{priority_level}} --{{instance}}"
    }
   ]
  }
 ]
}