{
 "title": "API Server Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "NS", "query": "default" },
   { "name": "APIService", "query": "apiserver" },
   { "name": "Instance", "query": "172.18.0.2:6443" }
  ]
 },
 "panels": [
  {
   "title": "99th Percentile of Request Duration",
   "type": "timeseries",
   "description": "averaged over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(verb, le) (rate(apiserver_request_duration_seconds_bucket{instance=\"$Instance\", job=\"$APIService\", namespace=\"$NS\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Percent Over Last 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{instance=\"$Instance\", job=\"$APIService\", code=~\"[45]..\", namespace=\"$NS\"}[5m])) * 100/sum(rate(apiserver_request_total{instance=\"$Instance\", job=\"$APIService\", namespace=\"$NS\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "averaged over the last 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$Instance\", job=~\"$APIService\", namespace=\"$NS\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Etcd Rquest Latency",
   "type": "timeseries",
   "description": "averaged over the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(etcd_request_duration_seconds_sum{instance=\"$Instance\", job=\"$APIService\", namespace=\"$NS\"}[1m])) / (rate(etcd_request_duration_seconds_count{instance=\"$Instance\", job=\"$APIService\", namespace=\"$NS\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Successful Requests to  the API server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{instance=\"$Instance\", job=\"$APIService\", namespace=\"$NS\", code=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Etcd Stored Objects per Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apiserver_storage_objects{instance=\"$Instance\", job=\"$APIService\", namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}