{
 "title": "KubeStellar Controllers Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SpaceNS", "query": "wds1-system" },
   {
    "name": "KSController",
    "query": "ks-controller-manager, ks-transport-controller, status-addon-controller"
   }
  ]
 },
 "panels": [
  {
   "title": "99th Percentile of Sync Duration for Items in the Workqueue ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, name, le) (rate(workqueue_queue_duration_seconds_bucket{namespace=\"$SpaceNS\", job=\"$KSController\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance, name) (rate(workqueue_depth{job=\"$KSController\", namespace=\"$SpaceNS\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile of Latencies on Requests to the API server.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(url, le) (rate(rest_client_request_duration_seconds_bucket{job=\"$KSController\", namespace=\"$SpaceNS\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client Requests from KS Controller by HTTP Response Code.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$KSController\", code=~\"2..\", namespace=\"$SpaceNS\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$KSController\", code=~\"3..\", namespace=\"$SpaceNS\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$KSController\", code=~\"4..\", namespace=\"$SpaceNS\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$KSController\", code=~\"5..\", namespace=\"$SpaceNS\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$KSController\", namespace=\"$SpaceNS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of Resident Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$KSController\", namespace=\"$SpaceNS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}