{
 "title": "KubeStellar Controllers Monitoring Average",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "NS", "query": "wds1-system" },
   {
    "name": "KSController",
    "query": "kubestellar-controller-manager-metrics-service, ks-transport-controller, status-addon-controller,status-agent-controller"
   },
   { "name": "Instance", "query": "172.30.11.65:8443" }
  ]
 },
 "panels": [
  {
   "title": "Average Sync Duration for Items in the Workqueue",
   "type": "timeseries",
   "description": "averaged over the last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(workqueue_queue_duration_seconds_sum{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}[1m])) / (rate(workqueue_queue_duration_seconds_count{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "workqueue_depth{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latencies on Requests to the API server",
   "type": "timeseries",
   "description": "averaged over the last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(rest_client_request_duration_seconds_sum{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}[1m])) / (rate(rest_client_request_duration_seconds_count{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of HTTP Client Requests from KS Controller by HTTP Response Code",
   "type": "timeseries",
   "description": "averaged over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{instance=\"$Instance\", job=\"$KSController\", code=~\"2..\", namespace=\"$NS\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{instance=\"$Instance\", job=\"$KSController\", code=~\"3..\", namespace=\"$NS\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{instance=\"$Instance\", job=\"$KSController\", code=~\"4..\", namespace=\"$NS\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{instance=\"$Instance\", job=\"$KSController\", code=~\"5..\", namespace=\"$NS\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "averaged over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Unfinished Work",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{instance=\"$Instance\", job=\"$KSController\", namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}