{
 "title": "WDS API Server Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SpaceNS", "query": "wds1-system" },
   { "name": "SpaceName", "query": "wds1" }
  ]
 },
 "panels": [
  {
   "title": "99th Percentile of Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(verb, le) (rate(apiserver_request_duration_seconds_bucket{job=\"$SpaceName\", namespace=\"$SpaceNS\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$SpaceName\", code=~\"[45]..\", namespace=\"$SpaceNS\"}[5m])) * 100/sum(rate(apiserver_request_total{job=\"$SpaceName\", namespace=\"$SpaceNS\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$SpaceName\", namespace=\"$SpaceNS\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Etcd Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le) (increase(etcd_request_duration_seconds_bucket{job=\"$SpaceName\", namespace=\"$SpaceNS\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Total Number of Requests to  the API server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$SpaceName\",code=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Etcd Stored Objects per Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "apiserver_storage_objects{job=\"$SpaceName\", namespace=\"$SpaceNS\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}