#!/usr/bin/env bash

# Copyright 2023 The KubeStellar Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cat <<EOF
Usage:
  kubectl kubestellar [command]

Available commands:
  deploy                  Deploy KubeStellar core in a Kubernetes cluster
  ensure                  Make sure a given thing exists and is setup
  get-internal-kubeconfig Fetch kubeconfig for using core from same namespace
  get-external-kubeconfig Fetch kubeconfig for using core from outside cluster
  prep-for-cluster        Ensure location and prep-for-syncer
  prep-for-syncer         First step in bootstrapping a WEC
  remove                  Make sure a given thing does not exist
EOF
