matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .github/spellcheck/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:  
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
      - script
      - style
      - a
      - img
      - href
      - meta
      - svg
      - title      
      - text
  - pyspelling.filters.text:
  sources:
  - '**/*.md'
  exclude:
  - '**/GOVERNANCE.md'
  default_encoding: utf-8
