//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	spacev1alpha1 "github.com/kubestellar/kubestellar/pkg/apis/space/v1alpha1"
	spacev1alpha1client "github.com/kubestellar/kubestellar/pkg/client/clientset/versioned/typed/space/v1alpha1"
)

// SpaceProviderDescsClusterGetter has a method to return a SpaceProviderDescClusterInterface.
// A group's cluster client should implement this interface.
type SpaceProviderDescsClusterGetter interface {
	SpaceProviderDescs() SpaceProviderDescClusterInterface
}

// SpaceProviderDescClusterInterface can operate on SpaceProviderDescs across all clusters,
// or scope down to one cluster and return a spacev1alpha1client.SpaceProviderDescInterface.
type SpaceProviderDescClusterInterface interface {
	Cluster(logicalcluster.Path) spacev1alpha1client.SpaceProviderDescInterface
	List(ctx context.Context, opts metav1.ListOptions) (*spacev1alpha1.SpaceProviderDescList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type spaceProviderDescsClusterInterface struct {
	clientCache kcpclient.Cache[*spacev1alpha1client.SpaceV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *spaceProviderDescsClusterInterface) Cluster(clusterPath logicalcluster.Path) spacev1alpha1client.SpaceProviderDescInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).SpaceProviderDescs()
}

// List returns the entire collection of all SpaceProviderDescs across all clusters.
func (c *spaceProviderDescsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*spacev1alpha1.SpaceProviderDescList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).SpaceProviderDescs().List(ctx, opts)
}

// Watch begins to watch all SpaceProviderDescs across all clusters.
func (c *spaceProviderDescsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).SpaceProviderDescs().Watch(ctx, opts)
}
