apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: %WDS%-ks-controller-manager
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - %WDS%-system
  selector:
    matchLabels:
      control-plane: controller-manager
