apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: %WDS%-ks-transport-controller
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - %WDS%-system
  selector:
    matchLabels:
      app: ks-transport-controller
