apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
  annotations:
    kubernetes.io/service-account.name: prometheus-kube-prometheus-prometheus
type: kubernetes.io/service-account-token
