apiVersion: v1
kind: Service
metadata:
  labels:
    app: status-agent
  name: status-agent-controller
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app: status-agent