apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kubestellar
    app.kubernetes.io/part-of: kubestellar
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-service
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: controller-manager
