{{- range .Values.WDSes }}
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: {{ .name }}
spec:
  backend: shared
  type: {{ .type | default "k8s" }}
  waitForPostCreateHooks: true
  postCreateHooks:
    - hookName: kubestellar-controller
      vars:
        APIGroups: "{{ .APIGroups | default "" }}"
    - hookName: transport-controller
  globalVars:
    ControlPlaneName: {{ .name }}
    ITSName: "{{ .ITSName | default "" }}"
{{- end }}