name: Bug Report
description: Create a report to help us improve
title: "bug: "
labels:
  - kind/bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Here is how you can help us serve you better:

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of the bug. See ["Making a Good Trouble Report"](https://docs.kubestellar.io/unreleased-development/direct/troubleshooting/#making-a-good-trouble-report).
      placeholder: |
        You might also look at the rest of the "Troubleshooting" page.
    validations:
      required: true

  - type: textarea
    id: snapshot
    attributes:
      label: Output from KubeStellar-Snapshot.sh
      description: | 
        Run kubestellar-snapshot.sh from the scripts directory and paste output here.
        Alternatively you can run the script remotely
        bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/refs/heads/main/scripts/kubestellar-snapshot.sh) -V -Y -L
        This will create kubestellar-snapshot.tar.gz which can be dragged and dropped into this text area.
      
  - type: textarea
    id: reproducing
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: checkboxes
    id: contribute
    attributes:
      label: Want to contribute?
      options:
        - label: I would like to work on this issue.
          required: false
          
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        If you are following some instructions, please give a pointer to them.
