name: KubeStellar Community Meeting Agenda
description: Create a new weekly meeting agenda
title: "KubeStellar Community Meeting [DATE]"
labels:
  - community-meeting
body:
  - type: textarea
    attributes:
      label: Overview
      value: |
        At 10am Eastern, 7am Pacific, 2pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T140000&p1=1440&p2=4826&p3=234&p4=195)

        Video call link: [https://ibm.webex.com/ibm/j.php?MTID=mc9015c89e56fb75fc0956a1bdb93f931](https://ibm.webex.com/ibm/j.php?MTID=mc9015c89e56fb75fc0956a1bdb93f931)
        Or dial: 1-844-531-0958 PIN: 145 377 9958#
        More phone numbers: https://ibm.webex.com/webappng/sites/ibm/meeting/scheduler
        Or join via SIP: sip:1453779958@ibm.webex.com

        Meeting recordings available on YouTube at https://kubestellar.io/tv

        Agenda is here: https://kubestellar.io/agenda
        (Join our mailing list at https://kubestellar.io/join_us to get access to the Agenda and other artifacts)
        
        Add topics you'd like to discuss below!

        Contributor Code of Conduct
           As contributors and maintainers in the CNCF community, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.

           We are committed to making participation in the CNCF community a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.
            
    validations:
      required: true
