name: Epic
description: For tracking a large feature, including how to demo it.
title: "epic: "
labels:
  - epic
body:
  - type: textarea
    id: objective
    attributes:
      label: Demo Objective
      description: Please describe the objective of your demo.
      placeholder: |
        - [ ] User should be able to ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Demo Steps
      description: Please describe the steps for the demo.
      placeholder: |
        1. Admin does X
        1. User does Y
        1. Everyone is happy :)

  - type: checkboxes
    id: action-items
    attributes:
      label: Action Items
      description: Please check the following
      options:
        - label: Scope of the current demo is necessary to fit in the prototype boundaries
          required: true
        - label: Contribute to the final demo script and recording

  - type: textarea
    id: stories
    attributes:
      label: Stories
      placeholder: |
        - [ ] (Example) Add new API group
        - [ ] (Example) Add Widget API type
        - [ ] (Example) Add WidgetController
        - [ ] (Example) **stretch-goal:** Add Widgets to `kubectl kcp` plugin
        - Out-of-scope (prototype x): Send Widgets to space
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **👋 Assignment Instructions**

        To assign yourself to this epic, please use the slash command:
        ```
        /assign
        ```

        This will automatically assign the epic to you via our Prow bot. You can also use `/unassign` to remove yourself from an epic.

        Thank you for your interest in contributing to KubeStellar! 🚀
