name: '🔒 Security Vulnerability'
description: 'Automated security vulnerability report from vulnerability scanning'
title: '[SECURITY]: '
labels:
  - kind/security
  - area/security
  - priority/important-soon
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ This is an automated security vulnerability report ⚠️**
        
        This issue was automatically created by the KubeStellar security vulnerability scanner.
        Please review and address according to our security response procedures.

  - type: textarea
    id: vulnerability-id
    attributes:
      label: 'Vulnerability ID'
      description: 'The CVE or vulnerability identifier'
      placeholder: 'CVE-2024-1234, GO-2024-1234, etc.'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 'Severity Level'
      description: 'Vulnerability severity assessment'
      options:
        - CRITICAL
        - HIGH
        - MEDIUM
        - LOW
    validations:
      required: true

  - type: dropdown
    id: scanner-type
    attributes:
      label: 'Scanner Type'
      description: 'Which scanner detected this vulnerability'
      options:
        - Trivy (Container/Filesystem)
        - govulncheck (Go Dependencies)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'Vulnerability Description'
      description: 'Detailed description of the vulnerability'
      placeholder: 'Description from the vulnerability database'
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: 'Affected Components'
      description: 'List of affected packages, versions, or components'
      render: markdown
      placeholder: |
        | Component | Current Version | Fixed Version |
        |-----------|----------------|---------------|
        | package-name | 1.0.0 | 1.0.1 |
    validations:
      required: true

  - type: textarea
    id: impact-assessment
    attributes:
      label: 'Impact Assessment'
      description: 'Assessment of how this vulnerability affects KubeStellar'
      placeholder: 'Potential impact on KubeStellar functionality, security, or operations'
    validations:
      required: false

  - type: textarea
    id: remediation
    attributes:
      label: 'Remediation Steps'
      description: 'Recommended steps to fix this vulnerability'
      placeholder: 'Steps to update dependencies, apply patches, or implement workarounds'
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 'References'
      description: 'Links to vulnerability databases, advisories, or additional information'
      render: markdown
      placeholder: |
        - [NVD Database](https://nvd.nist.gov/vuln/detail/CVE-XXXX)
        - [Go Vulnerability Database](https://pkg.go.dev/vuln/GO-XXXX)
    validations:
      required: false

  - type: checkboxes
    id: action-items
    attributes:
      label: 'Action Items'
      description: 'Security response checklist'
      options:
        - label: 'Vulnerability triaged and impact assessed'
        - label: 'Workarounds identified if available'
        - label: 'Fix/update plan developed'
        - label: 'Testing completed in development environment'
        - label: 'Fix deployed and verified'
        - label: 'Security scan re-run to confirm resolution'

  - type: markdown
    attributes:
      value: |
        ---
        
        **Security Contact Information:**
        - Email: kubestellar-security-announce@googlegroups.com
        - Security Policy: [SECURITY.md](https://github.com/kubestellar/kubestellar/blob/main/SECURITY.md)
        
        **SLA Expectations:**
        - CRITICAL: Address within 24 hours
        - HIGH: Address within 7 days
        - MEDIUM: Address within 30 days 