# Copyright 2024 The KubeStellar Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM registry.access.redhat.com/ubi9/ubi-minimal

ARG TARGETOS
ARG TARGETARCH
ARG VERSION

RUN [ "$VERSION" == "" ] && VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt) ; \
    curl -L \
        "https://dl.k8s.io/release/v${VERSION#v}/bin/${TARGETOS}/${TARGETARCH}/kubectl" \
	-o /usr/bin/kubectl && \
	chmod +x /usr/bin/kubectl

USER 1001

ENTRYPOINT [ "kubectl" ]
CMD [ "--help" ]
