---
apiVersion: test.kcp.io/v1alpha1
kind: Playground
spec:
  shards:
    - name: main
      workspaces:
        - name: root
          workspaces:
            - name: imw-1
              others:
                - name: sync-target-f
                  source:
                    file:
                      path: test/kubectl-kcp-playground/examples/kcp-edge/sync-target-f.yaml
                - name: sync-target-g
                  source:
                    file:
                      path: test/kubectl-kcp-playground/examples/kcp-edge/sync-target-g.yaml
              Locations:
                - name: location-f
                  labels:
                    env: prod
                  instanceSelector:
                    matchLabels:
                      example: "si"
                      extended: "non"
                - name: location-g
                  labels:
                    env: prod
                    extended: "si"
                  instanceSelector:
                    matchLabels: 
                      example: "si"
                      extended: "si"
            - name: espw
  pClusters:
    - name: florin
      type: kind
    - name: guilder
      type: kind
