---
apiVersion: test.kcp.io/v1alpha1
kind: Playground
spec:
  shards:
    - name: main
      workspaces:
        - name: root
          workspaces:
            # Stage 1
            - name: imw-1
              others:
                - name: sync-target-f
                  source:
                    file:
                      path: test/kubectl-kcp-playground/examples/kcp-edge/sync-target-f.yaml
                - name: sync-target-g
                  source:
                    file:
                      path: test/kubectl-kcp-playground/examples/kcp-edge/sync-target-g.yaml
              Locations:
                - name: location-f
                  labels:
                    env: prod
                  instanceSelector:
                    matchLabels:
                      example: "si"
                      extended: "non"
                - name: location-g
                  labels:
                    env: prod
                    extended: "si"
                  instanceSelector:
                    matchLabels: 
                      example: "si"
                      extended: "si"
            # Stage 2
            - name: espw
              others:
                - name: edgeCRD - edge.kcp.io_customizers
                  source:
                    file:
                      path: ../../../config/crds/edge.kcp.io_customizers.yaml
                - name: edge-CRD - edge.kcp.io_edgeplacements
                  source:
                    file:
                      path: ../../../config/crds/edge.kcp.io_edgeplacements.yaml
                - name: edge-CRD - edge.kcp.io_edgesyncconfigs
                  source:
                    file:
                      path: ../../../config/crds/edge.kcp.io_edgesyncconfigs.yaml
                - name: edge-CRD - edge.kcp.io_singleplacementslices
                  source:
                    file:
                      path: ../../../config/crds/edge.kcp.io_singleplacementslices.yaml
                - name: edge-CRD - edge.kcp.io_syncerconfigs
                  source:
                    file:
                      path: ../../../config/crds/edge.kcp.io_syncerconfigs.yaml
                - name: edge-CRD - meta.kcp.io_apiresources
                  source:
                    file:
                      path: ../../../config/crds/meta.kcp.io_apiresources.yaml
                - name: edge-Export - apiexport-edge.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiexport-edge.kcp.io.yaml
                - name: edge-Export - apiexport-meta.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiexport-meta.kcp.io.yaml
                - name: edge-Export - apiresourceschema-apiresources.meta.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiresourceschema-apiresources.meta.kcp.io.yaml
                - name: edge-Export - apiresourceschema-customizers.edge.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiresourceschema-customizers.edge.kcp.io.yaml
                - name: edge-Export - apiresourceschema-edgeplacements.edge.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiresourceschema-edgeplacements.edge.kcp.io.yaml
                - name: edge-Export - apiresourceschema-edgesyncconfigs.edge.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiresourceschema-edgesyncconfigs.edge.kcp.io.yaml
                - name: edge-Export - apiresourceschema-singleplacementslices.edge.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiresourceschema-singleplacementslices.edge.kcp.io.yaml
                - name: edge-Export - apiresourceschema-syncerconfigs.edge.kcp.io
                  source:
                    file:
                      path: ../../../config/exports/apiresourceschema-syncerconfigs.edge.kcp.io.yaml
            - name: my-org
              workspaces:
                - name: wmw-c
                  apiBindings:
                    - name: bind-kube
                      apiExport:
                        name: kubernetes
                        path: "root:compute"
                    - name: bind-edge
                      apiExport:
                        name: edge.kcp.io
                        path: "root:espw"
                  others:
                    - name: common_workload
                      source:
                        file:
                          path: test/kubectl-kcp-playground/examples/kcp-edge/common_workload.yaml
                    - name: edge-placement-c
                      source:
                        file:
                          path: test/kubectl-kcp-playground/examples/kcp-edge/edge-placement-c.yaml
                - name: wmw-s
                  apiBindings:
                    - name: bind-kube
                      apiExport:
                        name: kubernetes
                        path: "root:compute"
                    - name: bind-edge
                      apiExport:
                        name: edge.kcp.io
                        path: "root:espw"
                  others:
                    - name: special_workload
                      source:
                        file:
                          path: test/kubectl-kcp-playground/examples/kcp-edge/special_workload.yaml
                    - name: edge-placement-s
                      source:
                        file:
                          path: test/kubectl-kcp-playground/examples/kcp-edge/edge-placement-s.yaml

  pClusters:
    - name: florin
      type: kind
    - name: guilder
      type: kind
