apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: logicalcluster.kubestellar.io
spec:
  latestResourceSchemas:
  - v230625-22bb013a7.clusterproviderdescs.logicalcluster.kubestellar.io
  - v230625-22bb013a7.logicalclusters.logicalcluster.kubestellar.io
status: {}
