#!/usr/bin/env bash

# Copyright 2023 The KubeStellar Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Purpose: ensure that an inventory space exists and has the needed
# API bindings.

is_name=""
kubectl_flags=()
sub_flags=()

while (( $# > 0 )); do
    case "$1" in
	(-h|--help)
	    echo "Usage: $0 (-h | --help | -X | \$kubectl_flag --in-cluster | --output-kubeconfig \$pathname)* inventory_space_name"
	    exit 0;;
	(-X) set -o xtrace
	    sub_flags[${#sub_flags[*]}]="$1";;
	(--in-cluster)
	    sub_flags[${#sub_flags[*]}]="$1";;
	(--output-kubeconfig)
	    if (( $# >1 ))
	    then out_flag="$1 '$2'"; shift
	    else echo "$0: missing output kubeconfig value" >&2; exit 1
	    fi;;
	(-o|-o=*|--output|--output=*)
	    echo "$0: -o and --output flags are not supported" >&2; exit 1;;
	(--*=*|-?=*)
	    kubectl_flags[${#kubectl_flags[*]}]="$1";;
	(--*|-?)
	    kubectl_flags[${#kubectl_flags[*]}]="$1";
	    if (( $# > 1 )); then 
		 kubectl_flags[${#kubectl_flags[*]}]="$2"
		 shift
	    fi;;
	(-*)
	    echo "$0: flag syntax error" >&2
	    exit 1;;
	(*)
	    if [ -z "$is_name" ]
	    then is_name="$1"
	    else echo "$0: too many positional arguments" >&2
		 exit 1
	    fi
    esac
    shift
done

if [ "$is_name" == "" ]; then
    echo "$0: inventory space name not specified" >&2
    exit 1
fi

set -e

kubectl-kubestellar-space-ensure "${sub_flags[@]}" "${kubectl_flags[@]}" $is_name $out_flag

kubestellar-kube-bind "${sub_flags[@]}" "${kubectl_flags[@]}" "$is_name" "locations"
kubestellar-kube-bind "${sub_flags[@]}" "${kubectl_flags[@]}" "$is_name" "synctargets"
