#!/usr/bin/env bash
# Copyright 2023 The KubeStellar Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage: $0 (init or start or stop | -v)

# Purpose: control whether the controllers are running, setting up the ESPW if necessary.. The following components are created:
#           (a) 1 kcp workspace: edge service provider workspace (espw)
#           (b) 3 kubestellar controllers: kubestellar-where-resolver, mailbox-controller and placement-translator

# Pre-req: the space manager is running and there is a space provider
# named "default" and that is the one to use.

# Pre-req: `kubectl` with no flags will access the Space Management
# API Space (SMAS) with high privilege.

# Requirements:
#    Download KubeStellar binaries
#    KubeStellar controller binaries are on $PATH.

# Because of the direct way that `kubestellar-kube-bind` is
# implemented, all uses of that script --- direct and indirect,
# including the usage by this script --- must be made in the context
# of the same filesystem, working directory, and procsses space.

bindir=$(dirname $(realpath "${BASH_SOURCE[0]}"))

set -e

subcommand=""
verbosity=0
verbdir="&> /dev/null"
xflag=""
remove=0
cleanup=0
espw_name="espw"
log_folder=$(pwd)/kubestellar-logs
imws="root:imw1"
wmws="root:wmw1"
in_cluster=""

function echoerr() {
   echo "ERROR: $1" >&2
}

# Check if a given process name is running
process_running() {
  local SERVICE="$1"
  local NAME_LEN=${#SERVICE}
  local PGREP_FLAG
  if [ $NAME_LEN -gt 15 ]; then
    PGREP_FLAG="-f"
  else
    PGREP_FLAG="-x"
  fi
  if pgrep $PGREP_FLAG "$SERVICE" >/dev/null
  then
      echo "running"
  else
      echo "stopped"
  fi
}

wait_for_process(){
  local status=$(process_running $1)
  local MAX_RETRIES=10
  local retries=0
  local status_code=0
  while [ $status != "running" ]; do
      if [ $retries -eq $MAX_RETRIES ]; then
           status_code=1
           break
      fi

      retries=$(( retries + 1 ))
      sleep 3
      status=$(process_running $1)
  done
  echo $status_code
}

function ensure_imws() {
    local -a items
    while IFS=',' read -ra items; do
        for i in "${items[@]}"; do
            if [ "$i" == "" ] ; then
                continue
            fi

            imw=${i#"root:"}
            echo "Ensuring IMW: $imw"
            ${bindir}/kubectl-kubestellar-ensure-inventory_space $xflag $in_cluster $imw # &> /dev/null
        done
    done <<< "$1"
}


function ensure_wmws() {
    provider_type=$(kubectl get spaceproviderdesc default -o jsonpath='{$.spec.ProviderType}')
    if [ $provider_type = "kcp" ]; then
        echo "applying kube crds."
        kube_needed=true
    else
        kube_needed=false
	fi
    local -a items
    while IFS=',' read -ra items; do
        for i in "${items[@]}"; do
            if [ "$i" == "" ] ; then
                continue
            fi
            wmw=${i#"root:"}
            echo "Ensuring WMW: $wmw"
            ${bindir}/kubectl-kubestellar-ensure-wmw $xflag $in_cluster $wmw --with-kube $kube_needed # &> /dev/null
        done
    done <<< "$1"
}


while (( $# > 0 )); do
    case "$1" in
    (start|stop|init)
        subcommand=$1;;
    (--log-folder)
        if (( $# > 1 ));
        then { log_folder="$2"; shift; }
        else { echo "$0: missing log folder" >&2; exit 1; }
        fi;;
    (--verbose|-V)
        verbosity=1
	verbdir="";;
    (--ensure-imw)
        if (( $# > 1 ));
        then { imws="$2"; shift; }
        else { echo "$0: missing comma separated list of IMWs" >&2; exit 1; }
        fi;;
    (--ensure-wmw)
        if (( $# > 1 ));
        then { wmws="$2"; shift; }
        else { echo "$0: missing comma separated list of WMWs" >&2; exit 1; }
        fi;;
    (-X)
        xflag="-X"
        set -x;;
    (--in-cluster)
        in_cluster="--in-cluster";;
    (-h|--help)
        echo "Usage: $0 [init | start | stop] [--log-folder log_folder] [--ensure-imw imw-list] [--ensure-wmw wmw-list] [--provider-name provider-name] [-V|--verbose] [-h|--help] [-X] [--in-cluster]"
        exit 0;;
    (-*)
        echo "$0: unknown flag" >&2 ; exit 1;
        exit 1;;
    (*)
        echo "$0: unknown positional argument" >&2; exit 1;
        exit 1;;
    esac
    shift
done

if [ "$subcommand" == "" ]; then
    echo "$0: missing a subcommand" >&2
    exit 1
fi

function ensure_espw() {
    local kcs_kubeconfig="$(mktemp kcs.kubeconfig#XXXX)"
    kubectl-kubestellar-space-ensure $xflag $espw_name $in_cluster --output-kubeconfig $kcs_kubeconfig
    ensure_dex
    sleep 2
    ensure_kb_backend "$kcs_kubeconfig"
    KUBECONFIG=$kcs_kubeconfig kubectl apply -f "$bindir/../config/crds/"
    rm "$kcs_kubeconfig"
    echo "Finished populating the espw with kubestellar apiexports"
}

function ensure_dex() {
    if [ $(process_running dex) == "running" ]; then
        echo "dex is already running"
        return
    fi

    echo "starting dex in background"
    dex_config_file=$(dirname "$(which kubectl-bind)")/../hack/dex-config-dev.yaml
    if [[ -f dex_config_file ]]; then
        echo "Error looking for dex config file at $dex_config_file" >&2
    fi
    dex serve $dex_config_file &

    local run_status=$(wait_for_process dex)
    if [ $run_status -eq 0 ]; then
        echo "dex started"
    else
        echo "dex not started"
        exit 1
    fi
}

# ensure_kb_backend takes one positional parameter:
# - the file pathname of the kubeconfig to use for access to the KCS,
#   the caller may modify or delete this file after this function returns.
function ensure_kb_backend() {
    if [ $(process_running example-backend) == "running" ]; then
        echo "example-backend is already running"
        return
    fi

    echo "starting kube-bind example-backend in background"

    local kcs_kubeconfig="/tmp/kcs.kubeconfig"
    cp "$1" $kcs_kubeconfig
    
    ( 
        export KUBECONFIG="$kcs_kubeconfig"
        kubectl apply -f "$bindir/../kube-bind/deploy/crd"
        example-backend --oidc-issuer-client-id=kube-bind --oidc-issuer-client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0 --oidc-issuer-url=http://127.0.0.1:5556/dex --oidc-callback-url=http://127.0.0.1:8080/callback --pretty-name="BigCorp.com" --namespace-prefix="kube-bind-" --cookie-signing-key=bGMHz7SR9XcI9JdDB68VmjQErrjbrAR9JdVqjAOKHzE= --cookie-encryption-key=wadqi4u+w0bqnSrVFtM38Pz2ykYVIeeadhzT34XlC1Y= --consumer-scope="Cluster" &> /tmp/example-backend.log &
    )

    local run_status=$(wait_for_process example-backend)
    if [ $run_status -eq 0 ]; then
        echo "example-backend started"
    else
        echo "example-backend not started"
        exit 1
    fi
}
 
if [ "$subcommand" != init ]; then

    # Check mailbox-controller is already running
    if [ $(process_running mailbox-controller) == "running" ]
    then
	echo "An older deployment of mailbox-controller is already running - terminating it ...."
	pkill -f mailbox-controller
    fi

    # Check kubestellar-where-resolver is already running
    if [ $(process_running "kubestellar-where-resolver") == "running" ]
    then
	echo "An older deployment of kubestellar-where-resolver is already running - terminating it ...."
	pkill -f "kubestellar-where-resolver"
    fi

    # Check placement-translator is already running
    if [ $(process_running placement-translator) == "running" ]
    then
	echo "An older deployment of placement-translator is already running - terminating it ...."
	pkill -f placement-translator
    fi

fi

if [ $subcommand == stop ]; then
   echo "kubestellar stopped ....."
   exit 0
fi

ensure_espw
ensure_imws $imws
ensure_wmws $wmws

if [ $subcommand == init ]; then
    exit 0
fi


# Start the kubestellar controllers
echo "****************************************"
echo "Launching KubeStellar ..."
echo "****************************************"

sleep 5

# Create the logs directory
if [[ ! -d $log_folder ]]; then
    mkdir -p $log_folder
fi

# TODO: pass $in_cluster
mailbox-controller -v=2 >> $log_folder/mailbox-controller-log.txt 2>&1 &

run_status=$(wait_for_process mailbox-controller)
if [ $run_status -eq 0 ]; then
    echo " mailbox-controller is running (log file: $log_folder/mailbox-controller-log.txt)"
else
    echo " mailbox-controller failed to start ..... exiting"
    sleep 2
    exit 1
fi


# Start the kubestellar where-resolver
sleep 3
# TODO: pass $in_cluster
kubestellar-where-resolver -v 2 >> $log_folder/kubestellar-where-resolver-log.txt 2>&1 &

run_status=$(wait_for_process "kubestellar-where-resolver")
if [ $run_status -eq 0 ]; then
    echo " where-resolver is running (log file: $log_folder/kubestellar-where-resolver-log.txt)"
else
    echo " where-resolver failed to start ..... exiting"
    exit 1
fi

# Start the Placement Translator
sleep 3
# TODO: pass $in_cluster
placement-translator -v=2 >> $log_folder/placement-translator-log.txt 2>&1 &

run_status=$(wait_for_process placement-translator)
if [ $run_status -eq 0 ]; then
    echo " placement translator is running (log file: $log_folder/placement-translator-log.txt)"
else
    echo " placement translator failed to start ..... exiting"
    exit 1
fi

sleep 10
echo "****************************************"
echo "Finished launching KubeStellar ..."
echo "****************************************"

