//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"

	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	logicalclusterv1alpha1 "github.com/kubestellar/kubestellar/pkg/apis/logicalcluster/v1alpha1"
	kcplogicalclusterv1alpha1 "github.com/kubestellar/kubestellar/pkg/client/clientset/versioned/cluster/typed/logicalcluster/v1alpha1"
	logicalclusterv1alpha1client "github.com/kubestellar/kubestellar/pkg/client/clientset/versioned/typed/logicalcluster/v1alpha1"
)

var logicalClustersResource = schema.GroupVersionResource{Group: "logicalcluster.kubestellar.io", Version: "v1alpha1", Resource: "logicalclusters"}
var logicalClustersKind = schema.GroupVersionKind{Group: "logicalcluster.kubestellar.io", Version: "v1alpha1", Kind: "LogicalCluster"}

type logicalClustersClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *logicalClustersClusterClient) Cluster(clusterPath logicalcluster.Path) kcplogicalclusterv1alpha1.LogicalClustersNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &logicalClustersNamespacer{Fake: c.Fake, ClusterPath: clusterPath}
}

// List takes label and field selectors, and returns the list of LogicalClusters that match those selectors across all clusters.
func (c *logicalClustersClusterClient) List(ctx context.Context, opts metav1.ListOptions) (*logicalclusterv1alpha1.LogicalClusterList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(logicalClustersResource, logicalClustersKind, logicalcluster.Wildcard, metav1.NamespaceAll, opts), &logicalclusterv1alpha1.LogicalClusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &logicalclusterv1alpha1.LogicalClusterList{ListMeta: obj.(*logicalclusterv1alpha1.LogicalClusterList).ListMeta}
	for _, item := range obj.(*logicalclusterv1alpha1.LogicalClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested LogicalClusters across all clusters.
func (c *logicalClustersClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(logicalClustersResource, logicalcluster.Wildcard, metav1.NamespaceAll, opts))
}

type logicalClustersNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *logicalClustersNamespacer) Namespace(namespace string) logicalclusterv1alpha1client.LogicalClusterInterface {
	return &logicalClustersClient{Fake: n.Fake, ClusterPath: n.ClusterPath, Namespace: namespace}
}

type logicalClustersClient struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
	Namespace   string
}

func (c *logicalClustersClient) Create(ctx context.Context, logicalCluster *logicalclusterv1alpha1.LogicalCluster, opts metav1.CreateOptions) (*logicalclusterv1alpha1.LogicalCluster, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewCreateAction(logicalClustersResource, c.ClusterPath, c.Namespace, logicalCluster), &logicalclusterv1alpha1.LogicalCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*logicalclusterv1alpha1.LogicalCluster), err
}

func (c *logicalClustersClient) Update(ctx context.Context, logicalCluster *logicalclusterv1alpha1.LogicalCluster, opts metav1.UpdateOptions) (*logicalclusterv1alpha1.LogicalCluster, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateAction(logicalClustersResource, c.ClusterPath, c.Namespace, logicalCluster), &logicalclusterv1alpha1.LogicalCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*logicalclusterv1alpha1.LogicalCluster), err
}

func (c *logicalClustersClient) UpdateStatus(ctx context.Context, logicalCluster *logicalclusterv1alpha1.LogicalCluster, opts metav1.UpdateOptions) (*logicalclusterv1alpha1.LogicalCluster, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateSubresourceAction(logicalClustersResource, c.ClusterPath, "status", c.Namespace, logicalCluster), &logicalclusterv1alpha1.LogicalCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*logicalclusterv1alpha1.LogicalCluster), err
}

func (c *logicalClustersClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewDeleteActionWithOptions(logicalClustersResource, c.ClusterPath, c.Namespace, name, opts), &logicalclusterv1alpha1.LogicalCluster{})
	return err
}

func (c *logicalClustersClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewDeleteCollectionAction(logicalClustersResource, c.ClusterPath, c.Namespace, listOpts)

	_, err := c.Fake.Invokes(action, &logicalclusterv1alpha1.LogicalClusterList{})
	return err
}

func (c *logicalClustersClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*logicalclusterv1alpha1.LogicalCluster, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewGetAction(logicalClustersResource, c.ClusterPath, c.Namespace, name), &logicalclusterv1alpha1.LogicalCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*logicalclusterv1alpha1.LogicalCluster), err
}

// List takes label and field selectors, and returns the list of LogicalClusters that match those selectors.
func (c *logicalClustersClient) List(ctx context.Context, opts metav1.ListOptions) (*logicalclusterv1alpha1.LogicalClusterList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(logicalClustersResource, logicalClustersKind, c.ClusterPath, c.Namespace, opts), &logicalclusterv1alpha1.LogicalClusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &logicalclusterv1alpha1.LogicalClusterList{ListMeta: obj.(*logicalclusterv1alpha1.LogicalClusterList).ListMeta}
	for _, item := range obj.(*logicalclusterv1alpha1.LogicalClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *logicalClustersClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(logicalClustersResource, c.ClusterPath, c.Namespace, opts))
}

func (c *logicalClustersClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*logicalclusterv1alpha1.LogicalCluster, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewPatchSubresourceAction(logicalClustersResource, c.ClusterPath, c.Namespace, name, pt, data, subresources...), &logicalclusterv1alpha1.LogicalCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*logicalclusterv1alpha1.LogicalCluster), err
}
