# Dockerfile.rollout-checker
FROM docker.io/alpine/kubectl:1.34.1

# Install runtime dependencies and OCI CLI
RUN apk add --no-cache python3 py3-pip bash jq curl gettext \
    && pip install --break-system-packages --no-cache-dir oci-cli \
    && rm -rf /var/cache/apk/*

# (Optional) Print versions only during runtime, not build
# ENTRYPOINT ["bash", "-c", "kubectl version --client && oci --version && bash"]

WORKDIR /scripts
ENTRYPOINT ["/bin/bash"]

