/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/edge-mc/pkg/apis/edge/v1alpha1"
)

// FakeClusterProviderInfods implements ClusterProviderInfodInterface
type FakeClusterProviderInfods struct {
	Fake *FakeEdgeV1alpha1
}

var clusterproviderinfodsResource = schema.GroupVersionResource{Group: "edge.kcp.io", Version: "v1alpha1", Resource: "clusterproviderinfods"}

var clusterproviderinfodsKind = schema.GroupVersionKind{Group: "edge.kcp.io", Version: "v1alpha1", Kind: "ClusterProviderInfod"}

// Get takes name of the clusterProviderInfod, and returns the corresponding clusterProviderInfod object, and an error if there is any.
func (c *FakeClusterProviderInfods) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterProviderInfod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterproviderinfodsResource, name), &v1alpha1.ClusterProviderInfod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfod), err
}

// List takes label and field selectors, and returns the list of ClusterProviderInfods that match those selectors.
func (c *FakeClusterProviderInfods) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterProviderInfodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterproviderinfodsResource, clusterproviderinfodsKind, opts), &v1alpha1.ClusterProviderInfodList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterProviderInfodList{ListMeta: obj.(*v1alpha1.ClusterProviderInfodList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterProviderInfodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterProviderInfods.
func (c *FakeClusterProviderInfods) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterproviderinfodsResource, opts))
}

// Create takes the representation of a clusterProviderInfod and creates it.  Returns the server's representation of the clusterProviderInfod, and an error, if there is any.
func (c *FakeClusterProviderInfods) Create(ctx context.Context, clusterProviderInfod *v1alpha1.ClusterProviderInfod, opts v1.CreateOptions) (result *v1alpha1.ClusterProviderInfod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterproviderinfodsResource, clusterProviderInfod), &v1alpha1.ClusterProviderInfod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfod), err
}

// Update takes the representation of a clusterProviderInfod and updates it. Returns the server's representation of the clusterProviderInfod, and an error, if there is any.
func (c *FakeClusterProviderInfods) Update(ctx context.Context, clusterProviderInfod *v1alpha1.ClusterProviderInfod, opts v1.UpdateOptions) (result *v1alpha1.ClusterProviderInfod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterproviderinfodsResource, clusterProviderInfod), &v1alpha1.ClusterProviderInfod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfod), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterProviderInfods) UpdateStatus(ctx context.Context, clusterProviderInfod *v1alpha1.ClusterProviderInfod, opts v1.UpdateOptions) (*v1alpha1.ClusterProviderInfod, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterproviderinfodsResource, "status", clusterProviderInfod), &v1alpha1.ClusterProviderInfod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfod), err
}

// Delete takes name of the clusterProviderInfod and deletes it. Returns an error if one occurs.
func (c *FakeClusterProviderInfods) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterproviderinfodsResource, name, opts), &v1alpha1.ClusterProviderInfod{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterProviderInfods) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterproviderinfodsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterProviderInfodList{})
	return err
}

// Patch applies the patch and returns the patched clusterProviderInfod.
func (c *FakeClusterProviderInfods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterProviderInfod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterproviderinfodsResource, name, pt, data, subresources...), &v1alpha1.ClusterProviderInfod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfod), err
}
