/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/edge-mc/pkg/apis/edge/v1alpha1"
)

// FakeAssociators implements AssociatorInterface
type FakeAssociators struct {
	Fake *FakeEdgeV1alpha1
	ns   string
}

var associatorsResource = schema.GroupVersionResource{Group: "edge.kcp.io", Version: "v1alpha1", Resource: "associators"}

var associatorsKind = schema.GroupVersionKind{Group: "edge.kcp.io", Version: "v1alpha1", Kind: "Associator"}

// Get takes name of the associator, and returns the corresponding associator object, and an error if there is any.
func (c *FakeAssociators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Associator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(associatorsResource, c.ns, name), &v1alpha1.Associator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Associator), err
}

// List takes label and field selectors, and returns the list of Associators that match those selectors.
func (c *FakeAssociators) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AssociatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(associatorsResource, associatorsKind, c.ns, opts), &v1alpha1.AssociatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AssociatorList{ListMeta: obj.(*v1alpha1.AssociatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.AssociatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested associators.
func (c *FakeAssociators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(associatorsResource, c.ns, opts))

}

// Create takes the representation of a associator and creates it.  Returns the server's representation of the associator, and an error, if there is any.
func (c *FakeAssociators) Create(ctx context.Context, associator *v1alpha1.Associator, opts v1.CreateOptions) (result *v1alpha1.Associator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(associatorsResource, c.ns, associator), &v1alpha1.Associator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Associator), err
}

// Update takes the representation of a associator and updates it. Returns the server's representation of the associator, and an error, if there is any.
func (c *FakeAssociators) Update(ctx context.Context, associator *v1alpha1.Associator, opts v1.UpdateOptions) (result *v1alpha1.Associator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(associatorsResource, c.ns, associator), &v1alpha1.Associator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Associator), err
}

// Delete takes name of the associator and deletes it. Returns an error if one occurs.
func (c *FakeAssociators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(associatorsResource, c.ns, name, opts), &v1alpha1.Associator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAssociators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(associatorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AssociatorList{})
	return err
}

// Patch applies the patch and returns the patched associator.
func (c *FakeAssociators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Associator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(associatorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Associator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Associator), err
}
