/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/edge-mc/pkg/apis/edge/v1alpha1"
)

// FakeClusterProviderInfos implements ClusterProviderInfoInterface
type FakeClusterProviderInfos struct {
	Fake *FakeEdgeV1alpha1
}

var clusterproviderinfosResource = schema.GroupVersionResource{Group: "edge.kcp.io", Version: "v1alpha1", Resource: "clusterproviderinfos"}

var clusterproviderinfosKind = schema.GroupVersionKind{Group: "edge.kcp.io", Version: "v1alpha1", Kind: "ClusterProviderInfo"}

// Get takes name of the clusterProviderInfo, and returns the corresponding clusterProviderInfo object, and an error if there is any.
func (c *FakeClusterProviderInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterproviderinfosResource, name), &v1alpha1.ClusterProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfo), err
}

// List takes label and field selectors, and returns the list of ClusterProviderInfos that match those selectors.
func (c *FakeClusterProviderInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterProviderInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterproviderinfosResource, clusterproviderinfosKind, opts), &v1alpha1.ClusterProviderInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterProviderInfoList{ListMeta: obj.(*v1alpha1.ClusterProviderInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterProviderInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterProviderInfos.
func (c *FakeClusterProviderInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterproviderinfosResource, opts))
}

// Create takes the representation of a clusterProviderInfo and creates it.  Returns the server's representation of the clusterProviderInfo, and an error, if there is any.
func (c *FakeClusterProviderInfos) Create(ctx context.Context, clusterProviderInfo *v1alpha1.ClusterProviderInfo, opts v1.CreateOptions) (result *v1alpha1.ClusterProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterproviderinfosResource, clusterProviderInfo), &v1alpha1.ClusterProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfo), err
}

// Update takes the representation of a clusterProviderInfo and updates it. Returns the server's representation of the clusterProviderInfo, and an error, if there is any.
func (c *FakeClusterProviderInfos) Update(ctx context.Context, clusterProviderInfo *v1alpha1.ClusterProviderInfo, opts v1.UpdateOptions) (result *v1alpha1.ClusterProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterproviderinfosResource, clusterProviderInfo), &v1alpha1.ClusterProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterProviderInfos) UpdateStatus(ctx context.Context, clusterProviderInfo *v1alpha1.ClusterProviderInfo, opts v1.UpdateOptions) (*v1alpha1.ClusterProviderInfo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterproviderinfosResource, "status", clusterProviderInfo), &v1alpha1.ClusterProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfo), err
}

// Delete takes name of the clusterProviderInfo and deletes it. Returns an error if one occurs.
func (c *FakeClusterProviderInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterproviderinfosResource, name, opts), &v1alpha1.ClusterProviderInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterProviderInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterproviderinfosResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterProviderInfoList{})
	return err
}

// Patch applies the patch and returns the patched clusterProviderInfo.
func (c *FakeClusterProviderInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterproviderinfosResource, name, pt, data, subresources...), &v1alpha1.ClusterProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderInfo), err
}
