/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/edge-mc/pkg/apis/edge/v1alpha1"
)

// FakeClusterProviderConfigs implements ClusterProviderConfigInterface
type FakeClusterProviderConfigs struct {
	Fake *FakeEdgeV1alpha1
}

var clusterproviderconfigsResource = schema.GroupVersionResource{Group: "edge.kcp.io", Version: "v1alpha1", Resource: "clusterproviderconfigs"}

var clusterproviderconfigsKind = schema.GroupVersionKind{Group: "edge.kcp.io", Version: "v1alpha1", Kind: "ClusterProviderConfig"}

// Get takes name of the clusterProviderConfig, and returns the corresponding clusterProviderConfig object, and an error if there is any.
func (c *FakeClusterProviderConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterproviderconfigsResource, name), &v1alpha1.ClusterProviderConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderConfig), err
}

// List takes label and field selectors, and returns the list of ClusterProviderConfigs that match those selectors.
func (c *FakeClusterProviderConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterProviderConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterproviderconfigsResource, clusterproviderconfigsKind, opts), &v1alpha1.ClusterProviderConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterProviderConfigList{ListMeta: obj.(*v1alpha1.ClusterProviderConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterProviderConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterProviderConfigs.
func (c *FakeClusterProviderConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterproviderconfigsResource, opts))
}

// Create takes the representation of a clusterProviderConfig and creates it.  Returns the server's representation of the clusterProviderConfig, and an error, if there is any.
func (c *FakeClusterProviderConfigs) Create(ctx context.Context, clusterProviderConfig *v1alpha1.ClusterProviderConfig, opts v1.CreateOptions) (result *v1alpha1.ClusterProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterproviderconfigsResource, clusterProviderConfig), &v1alpha1.ClusterProviderConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderConfig), err
}

// Update takes the representation of a clusterProviderConfig and updates it. Returns the server's representation of the clusterProviderConfig, and an error, if there is any.
func (c *FakeClusterProviderConfigs) Update(ctx context.Context, clusterProviderConfig *v1alpha1.ClusterProviderConfig, opts v1.UpdateOptions) (result *v1alpha1.ClusterProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterproviderconfigsResource, clusterProviderConfig), &v1alpha1.ClusterProviderConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterProviderConfigs) UpdateStatus(ctx context.Context, clusterProviderConfig *v1alpha1.ClusterProviderConfig, opts v1.UpdateOptions) (*v1alpha1.ClusterProviderConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterproviderconfigsResource, "status", clusterProviderConfig), &v1alpha1.ClusterProviderConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderConfig), err
}

// Delete takes name of the clusterProviderConfig and deletes it. Returns an error if one occurs.
func (c *FakeClusterProviderConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterproviderconfigsResource, name, opts), &v1alpha1.ClusterProviderConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterProviderConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterproviderconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterProviderConfigList{})
	return err
}

// Patch applies the patch and returns the patched clusterProviderConfig.
func (c *FakeClusterProviderConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterproviderconfigsResource, name, pt, data, subresources...), &v1alpha1.ClusterProviderConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProviderConfig), err
}
