/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/edge-mc/pkg/apis/edge/v1alpha1"
)

// FakeClientProviderInfos implements ClientProviderInfoInterface
type FakeClientProviderInfos struct {
	Fake *FakeEdgeV1alpha1
}

var clientproviderinfosResource = schema.GroupVersionResource{Group: "edge.kcp.io", Version: "v1alpha1", Resource: "clientproviderinfos"}

var clientproviderinfosKind = schema.GroupVersionKind{Group: "edge.kcp.io", Version: "v1alpha1", Kind: "ClientProviderInfo"}

// Get takes name of the clientProviderInfo, and returns the corresponding clientProviderInfo object, and an error if there is any.
func (c *FakeClientProviderInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClientProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clientproviderinfosResource, name), &v1alpha1.ClientProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientProviderInfo), err
}

// List takes label and field selectors, and returns the list of ClientProviderInfos that match those selectors.
func (c *FakeClientProviderInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClientProviderInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clientproviderinfosResource, clientproviderinfosKind, opts), &v1alpha1.ClientProviderInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClientProviderInfoList{ListMeta: obj.(*v1alpha1.ClientProviderInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClientProviderInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clientProviderInfos.
func (c *FakeClientProviderInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clientproviderinfosResource, opts))
}

// Create takes the representation of a clientProviderInfo and creates it.  Returns the server's representation of the clientProviderInfo, and an error, if there is any.
func (c *FakeClientProviderInfos) Create(ctx context.Context, clientProviderInfo *v1alpha1.ClientProviderInfo, opts v1.CreateOptions) (result *v1alpha1.ClientProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clientproviderinfosResource, clientProviderInfo), &v1alpha1.ClientProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientProviderInfo), err
}

// Update takes the representation of a clientProviderInfo and updates it. Returns the server's representation of the clientProviderInfo, and an error, if there is any.
func (c *FakeClientProviderInfos) Update(ctx context.Context, clientProviderInfo *v1alpha1.ClientProviderInfo, opts v1.UpdateOptions) (result *v1alpha1.ClientProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clientproviderinfosResource, clientProviderInfo), &v1alpha1.ClientProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientProviderInfo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClientProviderInfos) UpdateStatus(ctx context.Context, clientProviderInfo *v1alpha1.ClientProviderInfo, opts v1.UpdateOptions) (*v1alpha1.ClientProviderInfo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clientproviderinfosResource, "status", clientProviderInfo), &v1alpha1.ClientProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientProviderInfo), err
}

// Delete takes name of the clientProviderInfo and deletes it. Returns an error if one occurs.
func (c *FakeClientProviderInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clientproviderinfosResource, name, opts), &v1alpha1.ClientProviderInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClientProviderInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clientproviderinfosResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClientProviderInfoList{})
	return err
}

// Patch applies the patch and returns the patched clientProviderInfo.
func (c *FakeClientProviderInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClientProviderInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clientproviderinfosResource, name, pt, data, subresources...), &v1alpha1.ClientProviderInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientProviderInfo), err
}
