#!/usr/bin/env bash

# Usage: $0 --subject-alt-names=$names

# Assumes easy-rsa PKI with CA is at $PWD/pki.
# Creates server public cert and private key at
# pki/kcp-server.crt and pki/kcp-server.key.
# Creates an ed25519 key.
# Makes a cert good for 10000 days.

if [ $# != 1 ] || [[ "$1" != --subject-alt-names=?* ]]; then
    echo "Usage: $0 --subject-alt-names=\$names" >&2
    exit 1
fi

SAN="${1#--subject-alt-names=}"

FILE_NAME_BASE="kcp-${SAN//:/-}"

export EASYRSA_PKI=${PWD}/pki

rm -f "${EASYRSA_PKI}/reqs/${FILE_NAME_BASE}.req" "${EASYRSA_PKI}/issued/${FILE_NAME_BASE}.crt" "${EASYRSA_PKI}/private/${FILE_NAME_BASE}.key"
easyrsa --batch --use-algo=ec \
    --subject-alt-name="$SAN" \
    --days=10000 \
    build-server-full "$FILE_NAME_BASE" nopass
