#!/usr/bin/env bash
# Copyright 2023 The KCP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage: $0 (start or stop | -v)

# Purpose: control whether the controllers are running, setting up the ESPW if necessary.. The following components are created:
#           (a) 1 kcp workspace: edge service provider workspace (espw)
#           (b) 3 kubestellar controllers: kubestellar-scheduler, mailbox-controller and placement-translator

# Assumption: kcp server is running.

# Requirements:
#    Download KubeStellar binaries
#    KubeStellar controller binaries are on $PATH.


set -e

subcommand=""
verbosity=0
verbdir="&> /dev/null"
remove=0
cleanup=0
espw_name="espw"
log_folder=$(pwd)/kubestellar-logs

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

while (( $# > 0 )); do
    case "$1" in
    (start|stop|init)
        subcommand=$1;;
    (--log-folder)
        if (( $# > 1 ));
        then { log_folder="$2"; shift; }
        else { echo "$0: missing log folder" >&2; exit 1; }
        fi;;
    (--verbose|-V)
        verbosity=1
	verbdir="";;
    (-h|--help)
        echo "Usage: $0 [start| stop][--log-folder log_folder] [-V|--verbose]"
        exit 0;;
    (-*)
        echo "$0: unknown flag" >&2 ; exit 1;
        exit 1;;
    (*)
        echo "$0: unknown positional argument" >&2; exit 1;
        exit 1;;
    esac
    shift
done

if [ "$subcommand" == "" ]; then
    echo "$0: missing a subcommand" >&2
    exit 1
fi

# Check if a given process name is running
process_running() {
  SERVICE="$1"
  if pgrep -f "$SERVICE" >/dev/null
  then
      echo "running"
  else
      echo "stopped" 
  fi
}

# Check if kcp is running
if [ $(process_running kcp) != "running" ]
then
    echo "kcp is not running - please start it ...."
    exit 1
fi

function ensure_espw() {
    if kubectl get Workspace "$espw_name" &> /dev/null; then
	echo "espw workspace already exists -- using it:"
	kubectl ws "$espw_name"
    else 
        kubectl ws create "$espw_name" --enter
    fi
    kubectl apply -f $SCRIPT_DIR/../config/exports $verbdir
    echo "Finished populating the espw with kubestellar apiexports"   
}

kubectl ws root &> /dev/null

if [ "$subcommand" == init ]; then
    ensure_espw
    exit
fi

# Check mailbox-controller is already running
if [ $(process_running mailbox-controller) == "running" ]
then
    echo "An older deployment of mailbox-controller is already running - terminating it ...."
    pkill -f mailbox-controller
fi

# Check kubestellar-scheduler is already running
if [ $(process_running "kubestellar-scheduler") == "running" ]
then
    echo "An older deployment of kubestellar-scheduler is already running - terminating it ...."
    pkill -f "kubestellar-scheduler"
fi

# Check placement-translator is already running
if [ $(process_running placement-translator) == "running" ]
then
    echo "An older deployment of placement-translator is already running - terminating it ...."
    pkill -f placement-translator
fi

if [ $subcommand == stop ]; then    
   echo "kubestellar stopped ....."
   exit 0
fi


wait_for_process(){
  status=$(process_running $1)
  MAX_RETRIES=5
  retries=0
  status_code=0
  while [ $status != "running" ]; do
      if [ $retries -eq $MAX_RETRIES ]; then
           status_code=1
           break
      fi

      retries=$(( retries + 1 ))
      sleep 3
      status=$(process_running $1)
  done
  echo $status_code
}


# Start the kubestellar controllers
echo "****************************************"
echo "Launching KubeStellar ..."
echo "****************************************"


sleep 5

# Create the logs directory
if [[ ! -d $log_folder ]]; then
    mkdir -p $log_folder
fi

mailbox-controller -v=2 >& $log_folder/mailbox-controller-log.txt &

run_status=$(wait_for_process mailbox-controller)
if [ $run_status -eq 0 ]; then
    echo " mailbox-controller is running (log file: $log_folder/mailbox-controller-log.txt)"
else
    echo " mailbox-controller failed to start ..... exiting"
    sleep 2
    exit 1
fi


# Start the kubestellar scheduler
sleep 3
kubestellar-scheduler -v 2 >& $log_folder/kubestellar-scheduler-log.txt &

run_status=$(wait_for_process "kubestellar-scheduler")
if [ $run_status -eq 0 ]; then
    echo " scheduler is running (log file: $log_folder/kubestellar-scheduler-log.txt)"
else
    echo " scheduler failed to start ..... exiting"
    exit 1
fi
 
# Start the Placement Translator
sleep 3
placement-translator --allclusters-context  "system:admin" -v=2 >& $log_folder/placement-translator-log.txt &

run_status=$(wait_for_process placement-translator)
if [ $run_status -eq 0 ]; then
    echo " placement translator is running (log file: $log_folder/placement-translator-log.txt)"
else
    echo " placement translator failed to start ..... exiting"
    exit 1
fi

sleep 10
echo "****************************************"
echo "Finished launching KubeStellar ..."
echo "****************************************"
kubectl ws root

