/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v2alpha1 "github.com/kubestellar/kubestellar/pkg/apis/edge/v2alpha1"
	scheme "github.com/kubestellar/kubestellar/pkg/client/clientset/versioned/scheme"
)

// DownsyncWorkloadPartSlicesGetter has a method to return a DownsyncWorkloadPartSliceInterface.
// A group's client should implement this interface.
type DownsyncWorkloadPartSlicesGetter interface {
	DownsyncWorkloadPartSlices() DownsyncWorkloadPartSliceInterface
}

// DownsyncWorkloadPartSliceInterface has methods to work with DownsyncWorkloadPartSlice resources.
type DownsyncWorkloadPartSliceInterface interface {
	Create(ctx context.Context, downsyncWorkloadPartSlice *v2alpha1.DownsyncWorkloadPartSlice, opts v1.CreateOptions) (*v2alpha1.DownsyncWorkloadPartSlice, error)
	Update(ctx context.Context, downsyncWorkloadPartSlice *v2alpha1.DownsyncWorkloadPartSlice, opts v1.UpdateOptions) (*v2alpha1.DownsyncWorkloadPartSlice, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.DownsyncWorkloadPartSlice, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.DownsyncWorkloadPartSliceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.DownsyncWorkloadPartSlice, err error)
	DownsyncWorkloadPartSliceExpansion
}

// downsyncWorkloadPartSlices implements DownsyncWorkloadPartSliceInterface
type downsyncWorkloadPartSlices struct {
	client rest.Interface
}

// newDownsyncWorkloadPartSlices returns a DownsyncWorkloadPartSlices
func newDownsyncWorkloadPartSlices(c *EdgeV2alpha1Client) *downsyncWorkloadPartSlices {
	return &downsyncWorkloadPartSlices{
		client: c.RESTClient(),
	}
}

// Get takes name of the downsyncWorkloadPartSlice, and returns the corresponding downsyncWorkloadPartSlice object, and an error if there is any.
func (c *downsyncWorkloadPartSlices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.DownsyncWorkloadPartSlice, err error) {
	result = &v2alpha1.DownsyncWorkloadPartSlice{}
	err = c.client.Get().
		Resource("downsyncworkloadpartslices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DownsyncWorkloadPartSlices that match those selectors.
func (c *downsyncWorkloadPartSlices) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.DownsyncWorkloadPartSliceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.DownsyncWorkloadPartSliceList{}
	err = c.client.Get().
		Resource("downsyncworkloadpartslices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested downsyncWorkloadPartSlices.
func (c *downsyncWorkloadPartSlices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("downsyncworkloadpartslices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a downsyncWorkloadPartSlice and creates it.  Returns the server's representation of the downsyncWorkloadPartSlice, and an error, if there is any.
func (c *downsyncWorkloadPartSlices) Create(ctx context.Context, downsyncWorkloadPartSlice *v2alpha1.DownsyncWorkloadPartSlice, opts v1.CreateOptions) (result *v2alpha1.DownsyncWorkloadPartSlice, err error) {
	result = &v2alpha1.DownsyncWorkloadPartSlice{}
	err = c.client.Post().
		Resource("downsyncworkloadpartslices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(downsyncWorkloadPartSlice).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a downsyncWorkloadPartSlice and updates it. Returns the server's representation of the downsyncWorkloadPartSlice, and an error, if there is any.
func (c *downsyncWorkloadPartSlices) Update(ctx context.Context, downsyncWorkloadPartSlice *v2alpha1.DownsyncWorkloadPartSlice, opts v1.UpdateOptions) (result *v2alpha1.DownsyncWorkloadPartSlice, err error) {
	result = &v2alpha1.DownsyncWorkloadPartSlice{}
	err = c.client.Put().
		Resource("downsyncworkloadpartslices").
		Name(downsyncWorkloadPartSlice.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(downsyncWorkloadPartSlice).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the downsyncWorkloadPartSlice and deletes it. Returns an error if one occurs.
func (c *downsyncWorkloadPartSlices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("downsyncworkloadpartslices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *downsyncWorkloadPartSlices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("downsyncworkloadpartslices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched downsyncWorkloadPartSlice.
func (c *downsyncWorkloadPartSlices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.DownsyncWorkloadPartSlice, err error) {
	result = &v2alpha1.DownsyncWorkloadPartSlice{}
	err = c.client.Patch(pt).
		Resource("downsyncworkloadpartslices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
