/*
Copyright The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v1alpha1 "github.com/kubestellar/kubestellar/space-framework/pkg/apis/space/v1alpha1"
)

// SpaceProviderDescLister helps list SpaceProviderDescs.
// All objects returned here must be treated as read-only.
type SpaceProviderDescLister interface {
	// List lists all SpaceProviderDescs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SpaceProviderDesc, err error)
	// Get retrieves the SpaceProviderDesc from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.SpaceProviderDesc, error)
	SpaceProviderDescListerExpansion
}

// spaceProviderDescLister implements the SpaceProviderDescLister interface.
type spaceProviderDescLister struct {
	indexer cache.Indexer
}

// NewSpaceProviderDescLister returns a new SpaceProviderDescLister.
func NewSpaceProviderDescLister(indexer cache.Indexer) SpaceProviderDescLister {
	return &spaceProviderDescLister{indexer: indexer}
}

// List lists all SpaceProviderDescs in the indexer.
func (s *spaceProviderDescLister) List(selector labels.Selector) (ret []*v1alpha1.SpaceProviderDesc, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SpaceProviderDesc))
	})
	return ret, err
}

// Get retrieves the SpaceProviderDesc from the index for a given name.
func (s *spaceProviderDescLister) Get(name string) (*v1alpha1.SpaceProviderDesc, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("spaceproviderdesc"), name)
	}
	return obj.(*v1alpha1.SpaceProviderDesc), nil
}
