/*
Copyright 2024 The KubeStellar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	versioned "sample-controller/pkg/generated/clientset/versioned"
	internalinterfaces "sample-controller/pkg/generated/informers/externalversions/internalinterfaces"
	v2alpha1 "sample-controller/pkg/generated/listers/edge/v2alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	edgev2alpha1 "k8s.io/sample-controller/pkg/apis/edge/v2alpha1"
)

// PlacementDecisionInformer provides access to a shared informer and lister for
// PlacementDecisions.
type PlacementDecisionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v2alpha1.PlacementDecisionLister
}

type placementDecisionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPlacementDecisionInformer constructs a new informer for PlacementDecision type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPlacementDecisionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPlacementDecisionInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPlacementDecisionInformer constructs a new informer for PlacementDecision type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPlacementDecisionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV2alpha1().PlacementDecisions().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV2alpha1().PlacementDecisions().Watch(context.TODO(), options)
			},
		},
		&edgev2alpha1.PlacementDecision{},
		resyncPeriod,
		indexers,
	)
}

func (f *placementDecisionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPlacementDecisionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *placementDecisionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&edgev2alpha1.PlacementDecision{}, f.defaultInformer)
}

func (f *placementDecisionInformer) Lister() v2alpha1.PlacementDecisionLister {
	return v2alpha1.NewPlacementDecisionLister(f.Informer().GetIndexer())
}
