{{- if .Values.InstallPCHs }}
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: its-clusteradmin
  labels:
    kflex.kubestellar.io/cptype: its
spec:
  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{"{{.HookName}}"}}"
    spec:
      template:
        spec:
          containers:
            - name: clusteradm
              image: "quay.io/kubestellar/clusteradm:latest"
              imagePullPolicy: IfNotPresent
              env:
                - name: KUBECONFIG
                  value: "/etc/kube/{{ .globalVars.ITSkubeconfig }}"
              volumeMounts:
                - name: kubeconfig
                  mountPath: /etc/kube
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          volumes:
          - name: kubeconfig
            secret:
              secretName: "{{"{{.ITSSecretName}}"}}"
          restartPolicy: Never
      backoffLimit: 1
{{- end }}
