{{- if .Values.InstallPCHs }}
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: transport-controller
  labels:
    kflex.kubestellar.io/cptype: wds
spec:
  templates:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: '{{"{{.ControlPlaneName}}-transport-controller"}}'
    rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "list", "watch", "patch"]
    - apiGroups: ["tenancy.kflex.kubestellar.org"]
      resources: ["controlplanes"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["tenancy.kflex.kubestellar.org"]
      resources: ["controlplanes/status"]
      verbs: ["get", "patch", "update"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: '{{"{{.ControlPlaneName}}"}}-transport-controller'
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: '{{"{{.ControlPlaneName}}"}}-transport-controller'
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: '{{"{{.Namespace}}"}}'
  - apiVersion: v1
    kind: Secret
    metadata:
      name: its-kubeconfig
    type: Opaque
    data: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: transport-controller
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: transport-controller
      template:
        metadata:
          labels:
            name: transport-controller
        spec:
          initContainers:
          - name: wait-its-create
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            args:
              - wait
              - --for=create
              - cp
              - '{{"{{.ITSName}}"}}'
              - --timeout=300s
          - name: wait-its-ready
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            args:
              - wait
              - --for=condition=Ready
              - cp
              - '{{"{{.ITSName}}"}}'
              - --timeout=300s
          - name: copy-its-secret
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - 'kubectl get secret {{"{{.ITSSecretName}}"}} --namespace {{"{{.ITSSecretNamespace}}"}} -o yaml | sed "/ownerReferences:/,/^- /d;/namespace:/d;/creationTimestamp:/d;/uid:/d;/resourceVersion:/d;s/\(name: \).*/\1its-kubeconfig/" | kubectl apply -f -'
          containers:
          - name: transport-controller
            image: ghcr.io/kubestellar/kubestellar/ocm-transport-controller:{{ .Values.TRANSPORT_VERSION | default .Values.KUBESTELLAR_VERSION }}
            imagePullPolicy: IfNotPresent
            args:
            - --metrics-bind-address={{.Values.transport_controller.metrics_bind_addr}}
            - --pprof-bind-address={{.Values.transport_controller.pprof_bind_addr}}
            - --transport-kubeconfig=/etc/kube/its/{{"{{.ITSkubeconfig}}"}}
            - --transport-qps={{.Values.transport_controller.transport_qps}}
            - --transport-burst={{.Values.transport_controller.transport_burst}}
            - --wds-kubeconfig=/etc/kube/wds/{{"{{.WDSkubeconfig}}"}}
            - --wds-name={{"{{.ControlPlaneName}}"}}
            - --wds-qps={{.Values.transport_controller.wds_qps}}
            - --wds-burst={{.Values.transport_controller.wds_burst}}
            - -v={{.Values.verbosity.transport | default .Values.verbosity.default | default 4 }}
            - --max-num-wrapped={{.Values.transport_controller.max_num_wrapped}}
            - --max-size-wrapped={{.Values.transport_controller.max_size_wrapped}}
            volumeMounts:
            - name: wds-kubeconfig-volume
              mountPath: /etc/kube/wds
            - name: its-kubeconfig-volume
              mountPath: /etc/kube/its/
          volumes:
          - name: wds-kubeconfig-volume
            secret:
              secretName: '{{"{{.WDSSecretName}}"}}'
          - name: its-kubeconfig-volume
            secret:
              secretName: its-kubeconfig
{{- end }}
