{{- if .Values.InstallPCHs }}
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: transport-controller
  labels:
    kflex.kubestellar.io/cptype: wds
spec:
  templates:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: "{{"{{.ControlPlaneName}}-transport-controller"}}"
    rules:
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - tenancy.kflex.kubestellar.org
      resources:
      - controlplanes
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - tenancy.kflex.kubestellar.org
      resources:
      - controlplanes/status
      verbs:
      - get
      - patch
      - update
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: "{{"{{.ControlPlaneName}}"}}-transport-controller"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: "{{"{{.ControlPlaneName}}"}}-transport-controller"
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: "{{"{{.Namespace}}"}}"
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: transport-controller
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: transport-controller
      template:
        metadata:
          labels:
            name: transport-controller
        spec:
          initContainers:
          - name: setup-wds-kubeconfig
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                kubectl wait --for=condition=Ready controlplane {{.ControlPlaneName}} --timeout=120s && \
                key=$(kubectl get controlplane {{.ControlPlaneName}} -o=jsonpath='{.status.secretRef.inClusterKey}') && \
                secret_name=$(kubectl get controlplane {{.ControlPlaneName}} -o=jsonpath='{.status.secretRef.name}') && \
                secret_namespace=$(kubectl get controlplane {{.ControlPlaneName}} -o=jsonpath='{.status.secretRef.namespace}') && \
                until kubectl get secret $secret_name -n $secret_namespace -o=jsonpath="{.data.$key}" > /dev/null 2>&1; do echo "Waiting for secret $secret_name to be populated..."; sleep 5; done && \
                kubectl get secret $secret_name -n $secret_namespace -o=jsonpath="{.data.$key}" | base64 -d > /mnt/shared/wds-kubeconfig
            volumeMounts:
            - name: shared-volume
              mountPath: /mnt/shared
          - name: setup-its-kubeconfig
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                kubectl wait --for=condition=Ready controlplane {{.ITSName}} --timeout=120s && \
                key=$(kubectl get controlplane {{.ITSName}} -o=jsonpath='{.status.secretRef.inClusterKey}') && \
                secret_name=$(kubectl get controlplane {{.ITSName}} -o=jsonpath='{.status.secretRef.name}') && \
                secret_namespace=$(kubectl get controlplane {{.ITSName}} -o=jsonpath='{.status.secretRef.namespace}') && \
                until kubectl get secret $secret_name -n $secret_namespace -o=jsonpath="{.data.$key}" > /dev/null 2>&1; do echo "Waiting for secret $secret_name to be populated..."; sleep 5; done && \
                kubectl get secret $secret_name -n $secret_namespace -o=jsonpath="{.data.$key}" | base64 -d > /mnt/shared/transport-kubeconfig
            volumeMounts:
            - name: shared-volume
              mountPath: /mnt/shared
          containers:
          - name: transport-controller
            image: ghcr.io/kubestellar/kubestellar/ocm-transport-controller:{{ .Values.TRANSPORT_VERSION | default .Values.KUBESTELLAR_VERSION }}
            imagePullPolicy: IfNotPresent
            args:
            - --metrics-bind-address={{.Values.transport_controller.metrics_bind_addr}}
            - --pprof-bind-address={{.Values.transport_controller.pprof_bind_addr}}
            - --transport-kubeconfig=/mnt/shared/transport-kubeconfig
            - --transport-qps={{.Values.transport_controller.transport_qps}}
            - --transport-burst={{.Values.transport_controller.transport_burst}}
            - --wds-kubeconfig=/mnt/shared/wds-kubeconfig
            - --wds-name={{"{{.ControlPlaneName}}"}}
            - --wds-qps={{.Values.transport_controller.wds_qps}}
            - --wds-burst={{.Values.transport_controller.wds_burst}}
            - -v={{.Values.verbosity.transport | default .Values.verbosity.default | default 4 }}
            - --max-num-wrapped={{.Values.transport_controller.max_num_wrapped}}
            - --max-size-wrapped={{.Values.transport_controller.max_size_wrapped}}
            volumeMounts:
            - name: shared-volume
              mountPath: /mnt/shared
              readOnly: true
          volumes:
          - name: shared-volume
            emptyDir: {}
          
{{- end }} 