{{- if .Values.InstallPCHs }}
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: transport-controller
  labels:
    kflex.kubestellar.io/cptype: wds
spec:
  templates:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: '{{"{{.ControlPlaneName}}-transport-controller"}}'
    rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get"]
    - apiGroups: ["tenancy.kflex.kubestellar.org"]
      resources: ["controlplanes"]
      verbs: ["get", "watch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: '{{"{{.ControlPlaneName}}"}}-transport-controller'
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: '{{"{{.ControlPlaneName}}"}}-transport-controller'
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: '{{"{{.Namespace}}"}}'
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: transport-controller
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: transport-controller
      template:
        metadata:
          labels:
            name: transport-controller
        spec:
          initContainers:
          - name: wait-its-create
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            args:
              - wait
              - --for=create
              - cp/{{"{{.ITSName}}"}}
              - --timeout=300s
          - name: wait-its-ready
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            args:
              - wait
              - --for=condition=Ready
              - cp/{{"{{.ITSName}}"}}
              - --timeout=300s
          - name: copy-its-secret
            image: quay.io/kubestellar/kubectl:{{.Values.KUBECTL_VERSION}}
            command:
              - sh
              - -c
              - 'kubectl get secret {{"{{.ITSSecretName}}"}} --namespace {{"{{.ITSSecretNamespace}}"}} -o jsonpath="{.data.{{"{{.ITSSecretKey}}"}}}" | base64 --decode > /etc/kube/its/kubeconfig'
            volumeMounts:
            - name: its-kubeconfig-volume
              mountPath: /etc/kube/its/
          containers:
          - name: transport-controller
            image: ghcr.io/kubestellar/kubestellar/ocm-transport-controller:{{ .Values.TRANSPORT_VERSION | default .Values.KUBESTELLAR_VERSION }}
            args:
            - --metrics-bind-address={{.Values.transport_controller.metrics_bind_addr}}
            - --pprof-bind-address={{.Values.transport_controller.pprof_bind_addr}}
            - --transport-kubeconfig=/etc/kube/its/kubeconfig
            - --transport-qps={{.Values.transport_controller.transport_qps}}
            - --transport-burst={{.Values.transport_controller.transport_burst}}
            - --wds-kubeconfig=/etc/kube/wds/{{"{{.WDSSecretKey}}"}}
            - --wds-name={{"{{.ControlPlaneName}}"}}
            - --wds-qps={{.Values.transport_controller.wds_qps}}
            - --wds-burst={{.Values.transport_controller.wds_burst}}
            - -v={{.Values.verbosity.transport | default .Values.verbosity.default | default 4 }}
            - --max-num-wrapped={{.Values.transport_controller.max_num_wrapped}}
            - --max-size-wrapped={{.Values.transport_controller.max_size_wrapped}}
            volumeMounts:
            - name: wds-kubeconfig-volume
              mountPath: /etc/kube/wds
              readOnly: True
            - name: its-kubeconfig-volume
              mountPath: /etc/kube/its/
              readOnly: True
          volumes:
          - name: wds-kubeconfig-volume
            secret:
              secretName: '{{"{{.WDSSecretName}}"}}'
          - name: its-kubeconfig-volume
            emptyDir:
              medium: Memory
{{- end }}
