name: Add new contributors to readme.md

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contributors in README
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch
        run: |
          BRANCH_NAME="update-contributors-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Amend Commit with Signed-off-by
        run: |
          git commit --amend --no-edit --signoff || echo "No changes to amend"

      - name: Push Changes to a New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --set-upstream origin $BRANCH_NAME

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.BRANCH_NAME }}
          title: "Update Contributors"
          body: "This PR updates the contributors list in README.md."
