name: docs-ecutable - Syncer
run-name: docs-ecutable - Syncer - ${{ github.ref_name }}

on:
  workflow_call:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - "release-0.1*"
      - space-mgt
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer.md"
      - "docs/content/Coding Milestones/PoC2023q1/example1-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-syncer.yml"
      - "docs/scripts/docs-ecutable.sh"
  push:
    branches:
      - space-mgt
      - "release-0.1*"
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer.md"
      - "docs/content/Coding Milestones/PoC2023q1/example1-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-syncer.yml"
      - "docs/scripts/docs-ecutable.sh"
    tags:
      - 'v0.1*'

env:
  docs-ecutable-filename: syncer
  docs-ecutable-md-filename: "'docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer.md'"

jobs:
  docs-ecutable:
    #if: github.repository_owner == 'kubestellar'
    name: docs-ecutable - for syncer e2e
    runs-on: ubuntu-latest
    outputs:
      docs-ecutable-filename: ${{ steps.step1.outputs.docs-ecutable-filename }}
    steps:
      - id: step1
        run: echo "docs-ecutable-filename=${{ env.docs-ecutable-filename }}" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.step1.outputs.docs-ecutable-filename }}

      - uses: actions/checkout@v4.1.1
      
      - uses: actions/setup-go@v5
        with:
          go-version: v1.19
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
  
      - run: |
          make MANIFEST="${{ env.docs-ecutable-md-filename }}" \
          docs-ecutable
