name: docs-ecutable - User Quickstart Kind
run-name: docs-ecutable - User Quickstart Kind - ${{ github.ref_name }}

on:
  workflow_call:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - "release-0.1*"
    paths:
      - "docs/content/Getting-Started/user-quickstart-kind.md"
      - "docs/content/Getting-Started/quickstart-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-user-quickstart-kind.yml"
      - "docs/scripts/docs-ecutable.sh"
  push:
    branches:
      - "release-0.1*"
    paths:
      - "docs/content/Getting-Started/user-quickstart-kind.md"
      - "docs/content/Getting-Started/quickstart-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-user-quickstart-kind.yml"
      - "docs/scripts/docs-ecutable.sh"
    tags:
      - 'v0.1*'
  #   branches:
  #     - main
  #     - "release-*"
  # push:
  #   branches:
  #     - main
  #     - "release-*"
  #   tags:
  #     - 'v*'
      
env:
  docs-ecutable-filename: user-quickstart-kind
  docs-ecutable-md-filename: "'docs/content/Getting-Started/user-quickstart-kind.md'"

jobs:
  docs-ecutable:
    #if: github.repository_owner == 'kubestellar'
    name: docs-ecutable - for user-quickstart-kind e2e
    runs-on: ubuntu-latest
    outputs:
      docs-ecutable-filename: ${{ steps.step1.outputs.docs-ecutable-filename }}
    steps:
      - id: step1
        run: echo "docs-ecutable-filename=${{ env.docs-ecutable-filename }}" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.step1.outputs.docs-ecutable-filename }}

      - uses: actions/checkout@v4.1.1
      
      - uses: actions/setup-go@v5
        with:
          go-version: v1.19
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install

        # with:
          # version: 'v1.27.4'
      - run: kubectl version || true

      # - run: sudo apt install coreutils

      - name: 🔎 Check IP
        run: curl https://api.ipify.org

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo $(tail -n 1 /etc/hosts | awk '{print $1}') kubestellar.core | sudo tee -a /etc/hosts
        # sudo echo $(curl https://api.ipify.org) kubestellar.core | sudo tee -a /etc/hosts

      - run: more /etc/hosts
      
      - run: |
          make MANIFEST="${{ env.docs-ecutable-md-filename }}" \
          docs-ecutable
