name: Docs PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - 'docs/**'      # Adjust if your docs are elsewhere
      

permissions:
  contents: write        # To push preview branches to gh-pages
  pull-requests: write   # To comment on the PR automatically

jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the PR code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python (matches your docs environment)
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies inside virtual environment
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r docs/requirements.txt

      # Step 4: Build documentation site
      - name: Build documentation
        run: |
          source venv/bin/activate
          mkdocs build --site-dir build/

      # Step 5: Deploy preview to gh-pages branch under pr-preview path
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
