name: PR Verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  verify:
    permissions:
      checks: write
      pull-requests: read
      packages: read
    uses: kubestellar/infra/.github/workflows/reusable-pr-verifier.yml@main
    secrets: inherit
