name: Add sbom

on:
  workflow_dispatch:
  workflow_run:
        workflows: [test-latest-release]
        types: [completed]

permissions: read-all

jobs:
    add-sbom:
        name: Add SBOM
        runs-on: ubuntu-latest
        if: ${{github.event.workflow_run.conclusion=='success'}}
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Create SBOM
              uses: advanced-security/sbom-generator-action@v0.0.1
              id: sbom
              env: 
                  GITHUB_TOKEN: ${{ github.token }}
              
            - name: Upload SBOM artefact
              uses: actions/upload-artifact@v3.1.0
              with: 
                path: ${{steps.sbom.outputs.fileName }}
                name: "SBOM"
